//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statline.Registry.Web.UI.Framework.Navigation {
    
    
    /// <summary>
    /// MenuControl class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class MenuControl {
        
        /// <summary>
        /// outerNavRegion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Statline.StatTrac.Web.UI.MasterPages.Region outerNavRegion;
        
        /// <summary>
        /// outerMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Statline.Registry.Web.UI.Framework.Navigation.OuterMenuControl outerMenuControl;
        
        /// <summary>
        /// innerNavRegion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Statline.StatTrac.Web.UI.MasterPages.Region innerNavRegion;
        
        /// <summary>
        /// innerMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Statline.Registry.Web.UI.Framework.Navigation.InnerMenuControl innerMenuControl;
    }
}
