// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Stattrac.Reporting.Models
{
    public partial class ShiftStatusContainer
    {
        public int ShiftStatus { get; set; }
    }
}