IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'InsertReferral')
BEGIN
	PRINT 'Dropping Procedure InsertReferral';
	DROP  Procedure  InsertReferral;
END
GO

PRINT 'Creating Procedure InsertReferral';
GO
CREATE Procedure [dbo].[InsertReferral]
    @ReferralID int = NULL , 
    @CallID int = NULL , 
    @ReferralCallerPhoneID int = NULL , 
    @ReferralCallerExtension varchar(10) = NULL , 
    @ReferralCallerOrganizationID int = NULL , 
    @ReferralCallerSubLocationID int = NULL , 
    @ReferralCallerSubLocationLevel varchar(4) = NULL , 
    @ReferralCallerPersonID int = NULL , 
    @ReferralDonorName varchar(80) = NULL , 
    @ReferralDonorRecNumber varchar(30) = NULL , 
    @ReferralDonorRecNumberSearchable varchar(30) = NULL , 
    @ReferralDonorAge varchar(4) = NULL , 
    @ReferralDonorAgeUnit varchar(10) = NULL , 
    @ReferralDonorRaceID int = NULL , 
    @ReferralDonorGender char(1) = NULL , 
    @ReferralDonorWeight varchar(7) = NULL , 
    @ReferralDonorAdmitDate smalldatetime = NULL , 
    @ReferralDonorAdmitTime varchar(10) = NULL , 
    @ReferralDonorDeathDate smalldatetime = NULL , 
    @ReferralDonorDeathTime varchar(10) = NULL ,
    @ReferralDonorLSADate smalldatetime = NULL , 
    @ReferralDonorLSATime varchar(10) = NULL ,
    @ReferralDonorCauseOfDeathID int = NULL , 
    @ReferralDonorOnVentilator varchar(20) = NULL , 
    @ReferralDonorDead varchar(4) = NULL , 
    @ReferralTypeID int = NULL , 
    @ReferralApproachTypeID int = NULL , 
    @ReferralApproachedByPersonID int = NULL , 
    @ReferralApproachNOK varchar(50) = NULL , 
    @ReferralApproachRelation varchar(50) = NULL , 
    @ReferralOrganAppropriateID int = NULL , 
    @ReferralOrganApproachID int = NULL , 
    @ReferralOrganConsentID int = NULL , 
    @ReferralOrganConversionID int = NULL , 
    @ReferralBoneAppropriateID int = NULL , 
    @ReferralBoneApproachID int = NULL , 
    @ReferralBoneConsentID int = NULL , 
    @ReferralBoneConversionID int = NULL , 
    @ReferralTissueAppropriateID int = NULL , 
    @ReferralTissueApproachID int = NULL , 
    @ReferralTissueConsentID int = NULL , 
    @ReferralTissueConversionID int = NULL , 
    @ReferralSkinAppropriateID int = NULL , 
    @ReferralSkinApproachID int = NULL , 
    @ReferralSkinConsentID int = NULL , 
    @ReferralSkinConversionID int = NULL , 
    @ReferralEyesTransAppropriateID int = NULL , 
    @ReferralEyesTransApproachID int = NULL , 
    @ReferralEyesTransConsentID int = NULL , 
    @ReferralEyesTransConversionID int = NULL , 
    @ReferralEyesRschAppropriateID int = NULL , 
    @ReferralEyesRschApproachID int = NULL , 
    @ReferralEyesRschConsentID int = NULL , 
    @ReferralEyesRschConversionID int = NULL , 
    @ReferralValvesAppropriateID int = NULL , 
    @ReferralValvesApproachID int = NULL , 
    @ReferralValvesConsentID int = NULL , 
    @ReferralValvesConversionID int = NULL , 
    @ReferralNotesCase varchar(400) = NULL , 
    @ReferralNotesPrevious varchar(255) = NULL , 
    @ReferralVerifiedOptions smallint = NULL , 
    @ReferralCoronersCase smallint = NULL , 
    @Inactive smallint = NULL , 
    @ReferralCallerLevelID int = NULL , 
    @UnusedField1 smallint = NULL , 
    @ReferralDonorFirstName varchar(40) = NULL , 
    @ReferralDonorLastName varchar(40) = NULL , 
    @ReferralOrganDispositionID int = NULL , 
    @ReferralBoneDispositionID int = NULL , 
    @ReferralTissueDispositionID int = NULL , 
    @ReferralSkinDispositionID int = NULL , 
    @ReferralValvesDispositionID int = NULL , 
    @ReferralEyesDispositionID int = NULL , 
    @ReferralRschDispositionID int = NULL , 
    @ReferralAllTissueDispositionID int = NULL , 
    @ReferralPronouncingMD int = NULL , 
    @UnusedField3 int = NULL , 
    @ReferralNOKPhone varchar(14) = NULL , 
    @ReferralAttendingMD int = NULL , 
    @ReferralGeneralConsent smallint = NULL , 
    @ReferralNOKAddress varchar(255) = NULL , 
    @ReferralCoronerName varchar(80) = NULL , 
    @ReferralCoronerPhone varchar(14) = NULL , 
    @ReferralCoronerOrganization varchar(80) = NULL , 
    @ReferralCoronerNote varchar(255) = NULL , 
    @ReferralApproachTime numeric = NULL , 
    @ReferralConsentTime numeric = NULL , 
    @Unused smalldatetime = NULL , 
    @ReferralDOA smallint = NULL , 
    @ReferralDOB datetime = NULL , 
    @ReferralDonorSSN varchar(11) = NULL , 
    @ReferralExtubated varchar(15) = NULL , 
    @DonorRegistryType smallint = NULL , 
    @DonorRegId int = NULL , 
    @DonorDMVId int = NULL , 
    @DonorDMVTable varchar(255) = NULL , 
    @DonorIntentDone smallint = NULL , 
    @DonorFaxSent smallint = NULL , 
    @DonorDSNID smallint = NULL , 
    @ReferralDonorHeartBeat int = NULL , 
    @ReferralCoronerOrgID int = NULL , 
    @CurrentReferralTypeId int = NULL , 
    @ReferralDonorBrainDeathDate smalldatetime = NULL , 
    @ReferralDonorBrainDeathTime varchar(10) = NULL , 
    @ReferralPronouncingMDPhone varchar(14) = NULL , 
    @ReferralAttendingMDPhone varchar(14) = NULL , 
    @ReferralDOB_ILB smallint = NULL , 
    @ReferralDonorSpecificCOD varchar(250) = NULL , 
    @ReferralDonorNameMI varchar(2) = NULL , 
    @ReferralNOKID int = NULL , 
    @ReferralQAReviewComplete smallint = NULL , 
	@ReferralDCDPotential smallint = NULL ,
	@ReferralPendingCase smallint = 0 ,
	@ReferralPendingCaseCoordinator smallint = NULL ,
	@ReferralPendingCaseComment varchar(50) = NULL ,
	@Hiv int = NULL,
	@Aids int = NULL,
	@HepB int = NULL,
	@HepC int = NULL,
	@Ivda int = NULL,
	@IdentityUnknown int = NULL,
	@AgeEstimated int = NULL,
	@WeightEstimated int = NULL,
	@PastMedicalHistory varchar(950) = NULL,
	@AdmittingDiagnosis varchar(950) = NULL,
    @LastStatEmployeeID int , 
    @AuditLogTypeID int = NULL 
AS

/******************************************************************************
**		File: InsertReferral.sql 
**		Name: InsertReferral
**		Desc: 
**
**		This template can be customized:
**              
**		Return values:
** 
**		Called by:   
**              
**		Parameters:
**		Input							Output
**     ----------							-----------
**     see list above
**
**		Auth: Bret Knoll
**		Date: 5/30/2007
*******************************************************************************
**		Change History
*******************************************************************************
**		Date:		Author:				Description:
**		--------	--------			-------------------------------------------
**      5/30/2007	Bret Knoll			8.4.3.8 AuditTrail
**		11/072007	ccarroll			changed default value for ReferralAttendingMD
**										and ReferralPronouncingMD to -1 : AuditTrail consistency
**		09/06/2011	ccarroll			Added LSA Date Time CCRST151
**		01/22/2018	Mike Berenson		Added ReferralDCDPotential
**		10/02/2018	Serge Hurko			#61346 - Add new fields to StatTrac Referral Event Log
**		6/19/2019	Mike Berenson		Added field: ReferralDonorRecNumberSearchable
**		05/28/2020	Mike Berenson		Added fields for e-referral
*******************************************************************************/

INSERT
	Referral
	(
	CallID, 
	ReferralCallerPhoneID, 
	ReferralCallerExtension, 
	ReferralCallerOrganizationID, 
	ReferralCallerSubLocationID, 
	ReferralCallerSubLocationLevel, 
	ReferralCallerPersonID, 
	ReferralDonorName, 
	ReferralDonorRecNumber, 
	ReferralDonorRecNumberSearchable, 
	ReferralDonorAge, 
	ReferralDonorAgeUnit, 
	ReferralDonorRaceID, 
	ReferralDonorGender, 
	ReferralDonorWeight, 
	ReferralDonorAdmitDate, 
	ReferralDonorAdmitTime, 
	ReferralDonorDeathDate, 
	ReferralDonorDeathTime,
	ReferralDonorLSADate, 
	ReferralDonorLSATime,
	ReferralDonorCauseOfDeathID, 
	ReferralDonorOnVentilator, 
	ReferralDonorDead, 
	ReferralTypeID, 
	ReferralApproachTypeID, 
	ReferralApproachedByPersonID, 
	ReferralApproachNOK, 
	ReferralApproachRelation, 
	ReferralOrganAppropriateID, 
	ReferralOrganApproachID, 
	ReferralOrganConsentID, 
	ReferralOrganConversionID, 
	ReferralBoneAppropriateID, 
	ReferralBoneApproachID, 
	ReferralBoneConsentID, 
	ReferralBoneConversionID, 
	ReferralTissueAppropriateID, 
	ReferralTissueApproachID, 
	ReferralTissueConsentID, 
	ReferralTissueConversionID, 
	ReferralSkinAppropriateID, 
	ReferralSkinApproachID, 
	ReferralSkinConsentID, 
	ReferralSkinConversionID, 
	ReferralEyesTransAppropriateID, 
	ReferralEyesTransApproachID, 
	ReferralEyesTransConsentID, 
	ReferralEyesTransConversionID, 
	ReferralEyesRschAppropriateID, 
	ReferralEyesRschApproachID, 
	ReferralEyesRschConsentID, 
	ReferralEyesRschConversionID, 
	ReferralValvesAppropriateID, 
	ReferralValvesApproachID, 
	ReferralValvesConsentID, 
	ReferralValvesConversionID, 
	ReferralNotesCase, 
	ReferralNotesPrevious, 
	ReferralVerifiedOptions, 
	ReferralCoronersCase, 
	Inactive, 
	ReferralCallerLevelID, 
	LastModified, 
	UnusedField1, 
	ReferralDonorFirstName, 
	ReferralDonorLastName, 
	ReferralOrganDispositionID, 
	ReferralBoneDispositionID, 
	ReferralTissueDispositionID, 
	ReferralSkinDispositionID, 
	ReferralValvesDispositionID, 
	ReferralEyesDispositionID, 
	ReferralRschDispositionID, 
	ReferralAllTissueDispositionID, 
	ReferralPronouncingMD, 
	UnusedField3, 
	ReferralNOKPhone, 
	ReferralAttendingMD, 
	ReferralGeneralConsent, 
	ReferralNOKAddress, 
	ReferralCoronerName, 
	ReferralCoronerPhone, 
	ReferralCoronerOrganization, 
	ReferralCoronerNote, 
	ReferralApproachTime, 
	ReferralConsentTime, 
	Unused, 
	ReferralDOA, 
	ReferralDOB, 
	ReferralDonorSSN, 
	ReferralExtubated, 
	DonorRegistryType, 
	DonorRegId, 
	DonorDMVId, 
	DonorDMVTable, 
	DonorIntentDone, 
	DonorFaxSent, 
	DonorDSNID, 
	ReferralDonorHeartBeat, 
	ReferralCoronerOrgID, 
	CurrentReferralTypeId, 
	ReferralDonorBrainDeathDate, 
	ReferralDonorBrainDeathTime, 
	ReferralPronouncingMDPhone, 
	ReferralAttendingMDPhone, 
	ReferralDOB_ILB, 
	ReferralDonorSpecificCOD, 
	ReferralDonorNameMI, 
	ReferralNOKID, 
	ReferralQAReviewComplete, 
	ReferralDCDPotential,
	ReferralPendingCase,
	ReferralPendingCaseCoordinator,
	ReferralPendingCaseComment,
	ReferralPendingCaseLastModified,
	Hiv,
	Aids,
	HepB,
	HepC,
	Ivda,
	IdentityUnknown,
	AgeEstimated,
	WeightEstimated,
	PastMedicalHistory,
	AdmittingDiagnosis,
	LastStatEmployeeID, 
	AuditLogTypeID 
	
	)
VALUES
	(
	@CallID, 
	@ReferralCallerPhoneID, 
	@ReferralCallerExtension, 
	@ReferralCallerOrganizationID, 
	@ReferralCallerSubLocationID, 
	@ReferralCallerSubLocationLevel, 
	@ReferralCallerPersonID, 
	@ReferralDonorName, 
	@ReferralDonorRecNumber, 
	@ReferralDonorRecNumberSearchable, 
	@ReferralDonorAge, 
	@ReferralDonorAgeUnit, 
	@ReferralDonorRaceID, 
	@ReferralDonorGender, 
	@ReferralDonorWeight, 
	@ReferralDonorAdmitDate, 
	@ReferralDonorAdmitTime, 
	@ReferralDonorDeathDate, 
	@ReferralDonorDeathTime,
	@ReferralDonorLSADate, 
	@ReferralDonorLSATime,
	ISNULL(@ReferralDonorCauseOfDeathID, -1), 
	@ReferralDonorOnVentilator, 
	@ReferralDonorDead, 
	ISNULL(@CurrentReferralTypeId, 0), --@ReferralTypeID 
	ISNULL(@ReferralApproachTypeID, -1), 
	@ReferralApproachedByPersonID, 
	@ReferralApproachNOK, 
	@ReferralApproachRelation, 
	ISNULL(@ReferralOrganAppropriateID, -1),
	ISNULL(@ReferralOrganApproachID, -1), 
	ISNULL(@ReferralOrganConsentID, -1), 
	ISNULL(@ReferralOrganConversionID, -1), 
	ISNULL(@ReferralBoneAppropriateID, -1), 
	ISNULL(@ReferralBoneApproachID, -1), 
	ISNULL(@ReferralBoneConsentID, -1), 
	ISNULL(@ReferralBoneConversionID, -1), 
	ISNULL(@ReferralTissueAppropriateID, -1), 
	ISNULL(@ReferralTissueApproachID, -1), 
	ISNULL(@ReferralTissueConsentID, -1), 
	ISNULL(@ReferralTissueConversionID, -1), 
	ISNULL(@ReferralSkinAppropriateID, -1), 
	ISNULL(@ReferralSkinApproachID, -1), 
	ISNULL(@ReferralSkinConsentID, -1), 
	ISNULL(@ReferralSkinConversionID, -1), 
	ISNULL(@ReferralEyesTransAppropriateID, -1), 
	ISNULL(@ReferralEyesTransApproachID, -1), 
	ISNULL(@ReferralEyesTransConsentID, -1), 
	ISNULL(@ReferralEyesTransConversionID, -1), 
	ISNULL(@ReferralEyesRschAppropriateID, -1), 
	ISNULL(@ReferralEyesRschApproachID, -1), 
	ISNULL(@ReferralEyesRschConsentID, -1), 
	ISNULL(@ReferralEyesRschConversionID, -1), 
	ISNULL(@ReferralValvesAppropriateID, -1), 
	ISNULL(@ReferralValvesApproachID, -1), 
	ISNULL(@ReferralValvesConsentID, -1), 
	ISNULL(@ReferralValvesConversionID, -1), 
	@ReferralNotesCase, 
	@ReferralNotesPrevious, 
	@ReferralVerifiedOptions, 
	@ReferralCoronersCase, 
	@Inactive, 
	@ReferralCallerLevelID, 
	GetDate(), -- @LastModified, 
	@UnusedField1, 
	@ReferralDonorFirstName, 
	@ReferralDonorLastName, 
	-- @ReferralOrganDispositionID
	dbo.fn_CalculateOverallDisposition(
										1, -- 1 = Organ
										@ReferralOrganAppropriateID,
										@ReferralOrganApproachID, 
										@ReferralOrganConsentID, 
										@ReferralOrganConversionID
										), 
	-- @ReferralBoneDispositionID, 
	dbo.fn_CalculateOverallDisposition(
										2, -- 2 = Bone
										@ReferralBoneAppropriateID, 
										@ReferralBoneApproachID, 
										@ReferralBoneConsentID, 
										@ReferralBoneConversionID
										), 
	-- @ReferralTissueDispositionID, 
	dbo.fn_CalculateOverallDisposition(
										3, -- 3 = Tissue
										@ReferralTissueAppropriateID, 
										@ReferralTissueApproachID, 
										@ReferralTissueConsentID, 
										@ReferralTissueConversionID 
										), 
	-- @ReferralSkinDispositionID, 
	dbo.fn_CalculateOverallDisposition(
										4, -- 4 = Skin
										@ReferralSkinAppropriateID, 
										@ReferralSkinApproachID, 
										@ReferralSkinConsentID, 
										@ReferralSkinConversionID
										), 
	-- @ReferralValvesDispositionID, 
	dbo.fn_CalculateOverallDisposition(
										5, -- 5 = Valves
										@ReferralValvesAppropriateID, 
										@ReferralValvesApproachID, 
										@ReferralValvesConsentID, 
										@ReferralValvesConversionID
										), 										
	--@ReferralEyesTransAppropriateID, 
	dbo.fn_CalculateOverallDisposition(6, -- 6 = Eyes
										@ReferralEyesTransAppropriateID, 
										@ReferralEyesTransApproachID, 
										@ReferralEyesTransConsentID, 
										@ReferralEyesTransConversionID
										), 
	-- @ReferralRschDispositionID,
	dbo.fn_CalculateOverallDisposition(7, -- 7 = Other
										@ReferralEyesRschAppropriateID, 
										@ReferralEyesRschApproachID, 
										@ReferralEyesRschConsentID, 
										@ReferralEyesRschConversionID
										),	 
	9, -- @ReferralAllTissueDispositionID 9 = Unknown, 
	ISNULL(@ReferralPronouncingMD, -1), 
	@UnusedField3, 
	@ReferralNOKPhone, 
	ISNULL(@ReferralAttendingMD, -1), 
	ISNULL(@ReferralGeneralConsent, -1), 
	@ReferralNOKAddress, 
	@ReferralCoronerName, 
	@ReferralCoronerPhone, 
	@ReferralCoronerOrganization, 
	@ReferralCoronerNote, 
	@ReferralApproachTime, 
	@ReferralConsentTime, 
	@Unused, 
	@ReferralDOA, 
	@ReferralDOB, 
	@ReferralDonorSSN, 
	@ReferralExtubated, 
	@DonorRegistryType, 
	@DonorRegId, 
	@DonorDMVId, 
	@DonorDMVTable, 
	@DonorIntentDone, 
	@DonorFaxSent, 
	@DonorDSNID, 
	@ReferralDonorHeartBeat, 
	ISNULL(@ReferralCoronerOrgID, -1), 
	@CurrentReferralTypeId, 
	@ReferralDonorBrainDeathDate, 
	@ReferralDonorBrainDeathTime, 
	@ReferralPronouncingMDPhone, 
	@ReferralAttendingMDPhone, 
	@ReferralDOB_ILB, 
	@ReferralDonorSpecificCOD, 
	@ReferralDonorNameMI, 
	@ReferralNOKID, 
	@ReferralQAReviewComplete, 	
	@ReferralDCDPotential,
	ISNULL(@ReferralPendingCase, 0),
	@ReferralPendingCaseCoordinator,
	@ReferralPendingCaseComment,
	GETDATE(),
	@Hiv,
	@Aids,
	@HepB,
	@HepC,
	@Ivda,
	@IdentityUnknown,
	@AgeEstimated,
	@WeightEstimated,
	@PastMedicalHistory,
	@AdmittingDiagnosis,
	@LastStatEmployeeID, 
	1 -- @AuditLogTypeID, 1 = Create
	
	);	

SELECT
	ReferralID, 
	CallID, 
	ReferralCallerPhoneID, 
	ReferralCallerExtension, 
	ReferralCallerOrganizationID, 
	ReferralCallerSubLocationID, 
	ReferralCallerSubLocationLevel, 
	ReferralCallerPersonID, 
	ReferralDonorName, 
	ReferralDonorRecNumber, 
	ReferralDonorRecNumberSearchable, 
	ReferralDonorAge, 
	ReferralDonorAgeUnit, 
	ReferralDonorRaceID, 
	ReferralDonorGender, 
	ReferralDonorWeight, 
	ReferralDonorAdmitDate, 
	ReferralDonorAdmitTime, 
	ReferralDonorDeathDate, 
	ReferralDonorDeathTime,
	ReferralDonorLSADate, 
	ReferralDonorLSATime,
	ReferralDonorCauseOfDeathID, 
	ReferralDonorOnVentilator, 
	ReferralDonorDead, 
	ReferralTypeID, 
	ReferralApproachTypeID, 
	ReferralApproachedByPersonID, 
	ReferralApproachNOK, 
	ReferralApproachRelation, 
	ReferralOrganAppropriateID, 
	ReferralOrganApproachID, 
	ReferralOrganConsentID, 
	ReferralOrganConversionID, 
	ReferralBoneAppropriateID, 
	ReferralBoneApproachID, 
	ReferralBoneConsentID, 
	ReferralBoneConversionID, 
	ReferralTissueAppropriateID, 
	ReferralTissueApproachID, 
	ReferralTissueConsentID, 
	ReferralTissueConversionID, 
	ReferralSkinAppropriateID, 
	ReferralSkinApproachID, 
	ReferralSkinConsentID, 
	ReferralSkinConversionID, 
	ReferralEyesTransAppropriateID, 
	ReferralEyesTransApproachID, 
	ReferralEyesTransConsentID, 
	ReferralEyesTransConversionID, 
	ReferralEyesRschAppropriateID, 
	ReferralEyesRschApproachID, 
	ReferralEyesRschConsentID, 
	ReferralEyesRschConversionID, 
	ReferralValvesAppropriateID, 
	ReferralValvesApproachID, 
	ReferralValvesConsentID, 
	ReferralValvesConversionID, 
	ReferralNotesCase, 
	ReferralNotesPrevious, 
	ReferralVerifiedOptions, 
	ReferralCoronersCase, 
	Inactive, 
	ReferralCallerLevelID, 	
	UnusedField1, 
	ReferralDonorFirstName, 
	ReferralDonorLastName, 
	ReferralOrganDispositionID, 
	ReferralBoneDispositionID, 
	ReferralTissueDispositionID, 
	ReferralSkinDispositionID, 
	ReferralValvesDispositionID, 
	ReferralEyesDispositionID, 
	ReferralRschDispositionID, 
	ReferralAllTissueDispositionID, 
	ReferralPronouncingMD, 
	UnusedField3, 
	ReferralNOKPhone, 
	ReferralAttendingMD, 
	ReferralGeneralConsent, 
	ReferralNOKAddress, 
	ReferralCoronerName, 
	ReferralCoronerPhone, 
	ReferralCoronerOrganization, 
	ReferralCoronerNote, 
	ReferralApproachTime, 
	ReferralConsentTime, 
	Unused, 
	ReferralDOA, 
	ReferralDOB, 
	ReferralDonorSSN, 
	ReferralExtubated, 
	DonorRegistryType, 
	DonorRegId, 
	DonorDMVId, 
	DonorDMVTable, 
	DonorIntentDone, 
	DonorFaxSent, 
	DonorDSNID, 
	ReferralDonorHeartBeat, 
	ReferralCoronerOrgID, 
	CurrentReferralTypeId, 
	ReferralDonorBrainDeathDate, 
	ReferralDonorBrainDeathTime, 
	ReferralPronouncingMDPhone, 
	ReferralAttendingMDPhone, 
	ReferralDOB_ILB, 
	ReferralDonorSpecificCOD, 
	ReferralDonorNameMI, 
	ReferralNOKID, 
	ReferralQAReviewComplete,
	ReferralDcdPotential,
	ReferralPendingCase,
	ReferralPendingCaseCoordinator,
	ReferralPendingCaseComment,
	ReferralPendingCaseLastModified,
	Hiv,
	Aids,
	HepB,
	HepC,
	Ivda,
	IdentityUnknown,
	AgeEstimated,
	WeightEstimated,
	PastMedicalHistory,
	AdmittingDiagnosis
FROM 
	Referral 
WHERE
	ReferralID = SCOPE_IDENTITY(); 

GO

GRANT EXEC ON InsertReferral TO PUBLIC;
GO
