IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'InsertSecondary')
	BEGIN
		PRINT 'Dropping Procedure InsertSecondary'
		DROP  Procedure  InsertSecondary
	END

GO

PRINT 'Creating Procedure InsertSecondary'
GO
CREATE Procedure InsertSecondary
	@CallID int, 
	@SecondaryWhoAreWe varchar(25) = NULL, 
	@SecondaryNOKaware smallint = NULL, 
	@SecondaryFamilyConsent smallint = NULL, 
	@SecondaryFamilyInterested smallint = NULL, 
	@SecondaryNOKatHospital smallint = NULL, 
	@SecondaryEstTimeSinceLeft varchar(10) = NULL, 
	@SecondaryTimeLeftInMT varchar(10) = NULL, 
	@SecondaryNOKNextDest varchar(25) = NULL, 
	@SecondaryNOKETA varchar(10) = NULL, 
	@SecondaryPatientMiddleName varchar(25) = NULL, 
	@SecondaryPatientHeightFeet varchar(2) = NULL, 
	@SecondaryPatientHeightInches varchar(2) = NULL, 
	@SecondaryPatientBMICalc varchar(10) = NULL, 
	@SecondaryPatientTOD1 varchar(10) = NULL, 
	@SecondaryPatientTOD2 varchar(10) = NULL, 
	@SecondaryPatientDeathType1 smalldatetime = NULL, 
	@SecondaryPatientDeathType2 smalldatetime = NULL, 
	@SecondaryTriageHX varchar(255) = NULL, 
	@SecondaryCircumstanceOfDeath varchar(1000) = NULL, 
	@SecondaryMedicalHistory varchar(1000) = NULL, 
	@SecondaryAdmissionDiagnosis varchar(100) = NULL, 
	@SecondaryCOD int = NULL, 
	@SecondaryCODSignatory varchar(50) = NULL, 
	@SecondaryCODTime varchar(10) = NULL, 
	@SecondaryCODSignedBy varchar(25) = NULL, 
	@SecondaryPatientVent smallint = NULL, 
	@SecondaryIntubationDate smalldatetime = NULL, 
	@SecondaryIntubationTime varchar(10) = NULL, 
	@SecondaryBrainDeathDate smalldatetime = NULL, 
	@SecondaryBrainDeathTime varchar(10) = NULL, 
	@SecondaryDNRDate smalldatetime = NULL, 
	@SecondaryERORDeath smallint = NULL, 
	@SecondaryEMSArrivalToPatientDate smalldatetime = NULL, 
	@SecondaryEMSArrivalToPatientTime varchar(10) = NULL, 
	@SecondaryEMSArrivalToHospitalDate smalldatetime = NULL, 
	@SecondaryEMSArrivalToHospitalTime varchar(10) = NULL, 
	@SecondaryPatientTerminal smallint = NULL, 
	@SecondaryDeathWitnessed smallint = NULL, 
	@SecondaryDeathWitnessedBy varchar(50) = NULL, 
	@SecondaryLSADate smalldatetime = NULL, 
	@SecondaryLSATime varchar(10) = NULL, 
	@SecondaryLSABy varchar(25) = NULL, 
	@SecondaryACLSProvided smallint = NULL, 
	@SecondaryACLSProvidedTime varchar(10) = NULL, 
	@SecondaryGestationalAge varchar(10) = NULL, 
	@SecondaryParentName1 varchar(25) = NULL, 
	@SecondaryParentName2 varchar(25) = NULL, 
	@SecondaryBirthCBO varchar(10) = NULL, 
	@SecondaryActiveInfection smallint = NULL, 
	@SecondaryActiveInfectionType varchar(25) = NULL, 
	@SecondaryFluidsGiven smallint = NULL, 
	@SecondaryBloodLoss smallint = NULL, 
	@SecondarySignOfInfection smallint = NULL, 
	@SecondaryMedication smallint = NULL, 
	@SecondaryAntibiotic smallint = NULL, 
	@SecondaryPCPName varchar(50) = NULL, 
	@SecondaryPCPPhone varchar(14) = NULL, 
	@SecondaryMDAttending varchar(50) = NULL, 
	@SecondaryMDAttendingPhone varchar(14) = NULL, 
	@SecondaryPhysicalAppearance varchar(1000) = NULL, 
	@SecondaryInternalBloodLossCC varchar(10) = NULL, 
	@SecondaryExternalBloodLossCC varchar(10) = NULL, 
	@SecondaryBloodProducts smallint = NULL, 
	@SecondaryColloidsInfused smallint = NULL, 
	@SecondaryCrystalloids smallint = NULL, 
	@SecondaryPreTransfusionSampleRequired smallint = NULL, 
	@SecondaryPreTransfusionSampleAvailable smallint = NULL, 
	@SecondaryPreTransfusionSampleDrawnDate smalldatetime = NULL, 
	@SecondaryPreTransfusionSampleDrawnTime varchar(10) = NULL, 
	@SecondaryPreTransfusionSampleQuantity varchar(10) = NULL, 
	@SecondaryPreTransfusionSampleHeldAt varchar(25) = NULL, 
	@SecondaryPreTransfusionSampleHeldDate smalldatetime = NULL, 
	@SecondaryPreTransfusionSampleHeldTime varchar(10) = NULL, 
	@SecondaryPreTransfusionSampleHeldTechnician varchar(25) = NULL, 
	@SecondaryPostMordemSampleTestSuitable smallint = NULL, 
	@SecondaryPostMordemSampleLocation varchar(25) = NULL, 
	@SecondaryPostMordemSampleContact varchar(25) = NULL, 
	@SecondaryPostMordemSampleCollectionDate smalldatetime = NULL, 
	@SecondaryPostMordemSampleCollectionTime varchar(10) = NULL, 
	@SecondarySputumCharacteristics varchar(255) = NULL, 
	@SecondaryNOKAltPhone varchar(14) = NULL, 
	@SecondaryNOKLegal smallint = NULL, 
	@SecondaryNOKAltContact varchar(25) = NULL, 
	@SecondaryNOKAltContactPhone varchar(14) = NULL, 
	@SecondaryNOKPostMortemAuthorization smallint = NULL, 
	@SecondaryNOKPostMortemAuthorizationReminder varchar(25) = NULL, 
	@SecondaryCoronerCaseNumber varchar(25) = NULL, 
	@SecondaryCoronerCounty varchar(25) = NULL, 
	@SecondaryCoronerReleased varchar(25) = NULL, 
	@SecondaryCoronerReleasedStipulations varchar(255) = NULL, 
	@SecondaryAutopsy smallint = NULL, 
	@SecondaryAutopsyDate smalldatetime = NULL, 
	@SecondaryAutopsyTime varchar(10) = NULL, 
	@SecondaryAutopsyLocation int = NULL, 
	@SecondaryAutopsyBloodRequested smallint = NULL, 
	@SecondaryAutopsyCopyRequested smallint = NULL, 
	@SecondaryFuneralHomeSelected smallint = NULL, 
	@SecondaryFuneralHomeName varchar(100) = NULL, 
	@SecondaryFuneralHomePhone varchar(14) = NULL, 
	@SecondaryFuneralHomeAddress varchar(100) = NULL, 
	@SecondaryFuneralHomeContact varchar(25) = NULL, 
	@SecondaryFuneralHomeNotified varchar(2) = NULL, 
	@SecondaryFuneralHomeMorgueCooled varchar(2) = NULL, 
	@SecondaryHoldOnBody smallint = NULL, 
	@SecondaryHoldOnBodyTag varchar(25) = NULL, 
	@SecondaryBodyRefrigerationDate smalldatetime = NULL, 
	@SecondaryBodyRefrigerationTime varchar(10) = NULL, 
	@SecondaryBodyLocation varchar(25) = NULL, 
	@SecondaryBodyMedicalChartLocation varchar(25) = NULL, 
	@SecondaryBodyIDTagLocation varchar(25) = NULL, 
	@SecondaryBodyCoolingMethod varchar(50) = NULL, 
	@SecondaryUNOSNumber varchar(25) = NULL, 
	@SecondaryClientNumber varchar(25) = NULL, 
	@SecondaryCryolifeNumber varchar(25) = NULL, 
	@SecondaryMTFNumber varchar(25) = NULL, 
	@SecondaryLifeNetNumber varchar(25) = NULL, 
	@SecondaryFreeText varchar(255) = NULL, 
	@SecondaryHistorySubstanceAbuse smallint = NULL, 
	@SecondarySubstanceAbuseDetail varchar(255) = NULL, 
	@SecondaryExtubationDate smalldatetime = NULL, 
	@SecondaryExtubationTime varchar(10) = NULL, 
	@SecondaryAutopsyReminderYN smallint = NULL, 
	@SecondaryFHReminderYN smallint = NULL, 
	@SecondaryBodyCareReminderYN smallint = NULL, 
	@SecondaryWrapUpReminderYN smallint = NULL, 
	@SecondaryNOKNotifiedBy varchar(50) = NULL, 
	@SecondaryNOKNotifiedDate smalldatetime = NULL, 
	@SecondaryNOKNotifiedTime varchar(10) = NULL, 
	@SecondaryNOKGender varchar(50) = NULL, 
	@SecondaryCODOther varchar(200) = NULL, 
	@SecondaryAutopsyLocationOther varchar(100) = NULL, 
	@SecondaryPatientHospitalPhone varchar(14) = NULL, 
	@SecondaryCoronerCase smallint = NULL, 
	@SecondaryPatientABO int = NULL, 
	@SecondaryPatientSuffix varchar(10) = NULL, 
	@SecondaryMDAttendingId int = NULL, 
	@SecondaryAdditionalComments varchar(255) = NULL, 
	@SecondaryRhythm int = NULL, 
	@SecondaryAdditionalMedications varchar(150) = NULL, 
	@SecondaryBodyHoldPlaced smalldatetime = NULL, 
	@SecondaryBodyHoldPlacedWith varchar(25) = NULL, 
	@SecondaryBodyFutureContact varchar(25) = NULL, 
	@SecondaryBodyHoldPhone varchar(14) = NULL, 
	@SecondaryBodyHoldInstructionsGiven smallint = NULL, 
	@SecondarySteroid smallint = NULL, 
	@SecondaryBodyHoldPlacedTime varchar(10) = NULL, 
	@LastStatEmployeeID int, 
	@AuditLogTypeID int = NULL

AS

/******************************************************************************
**		File: InsertSecondary.sql
**		Name: InsertSecondary
**		Desc: 
**
**
**              
**		Return values:
** 
**		Called by:   
**              
**		Parameters:
**		Input							Output
**     ----------							-----------
**     see list above
**
**		Auth: Bret Knoll
**		Date: 5/30/2007
*******************************************************************************
**		Change History
*******************************************************************************
**		Date:		Author:				Description:
**		--------	--------			-------------------------------------------
**      5/30/2007	Bret Knoll			8.4.3.8 AuditTrail
*******************************************************************************/
INSERT 
	Secondary 
	( 
		CallID,
		SecondaryWhoAreWe,
		SecondaryNOKaware,
		SecondaryFamilyConsent,
		SecondaryFamilyInterested,
		SecondaryNOKatHospital,
		SecondaryEstTimeSinceLeft,
		SecondaryTimeLeftInMT,
		SecondaryNOKNextDest,
		SecondaryNOKETA,
		SecondaryPatientMiddleName,
		SecondaryPatientHeightFeet,
		SecondaryPatientHeightInches,
		SecondaryPatientBMICalc,
		SecondaryPatientTOD1,
		SecondaryPatientTOD2,
		SecondaryPatientDeathType1,
		SecondaryPatientDeathType2,
		SecondaryTriageHX,
		SecondaryCircumstanceOfDeath,
		SecondaryMedicalHistory,
		SecondaryAdmissionDiagnosis,
		SecondaryCOD,
		SecondaryCODSignatory,
		SecondaryCODTime,
		SecondaryCODSignedBy,
		SecondaryPatientVent,
		SecondaryIntubationDate,
		SecondaryIntubationTime,
		SecondaryBrainDeathDate,
		SecondaryBrainDeathTime,
		SecondaryDNRDate,
		SecondaryERORDeath,
		SecondaryEMSArrivalToPatientDate,
		SecondaryEMSArrivalToPatientTime,
		SecondaryEMSArrivalToHospitalDate,
		SecondaryEMSArrivalToHospitalTime,
		SecondaryPatientTerminal,
		SecondaryDeathWitnessed,
		SecondaryDeathWitnessedBy,
		SecondaryLSADate,
		SecondaryLSATime,
		SecondaryLSABy,
		SecondaryACLSProvided,
		SecondaryACLSProvidedTime,
		SecondaryGestationalAge,
		SecondaryParentName1,
		SecondaryParentName2,
		SecondaryBirthCBO,
		SecondaryActiveInfection,
		SecondaryActiveInfectionType,
		SecondaryFluidsGiven,
		SecondaryBloodLoss,
		SecondarySignOfInfection,
		SecondaryMedication,
		SecondaryAntibiotic,
		SecondaryPCPName,
		SecondaryPCPPhone,
		SecondaryMDAttending,
		SecondaryMDAttendingPhone,
		SecondaryPhysicalAppearance,
		SecondaryInternalBloodLossCC,
		SecondaryExternalBloodLossCC,
		SecondaryBloodProducts,
		SecondaryColloidsInfused,
		SecondaryCrystalloids,
		SecondaryPreTransfusionSampleRequired,
		SecondaryPreTransfusionSampleAvailable,
		SecondaryPreTransfusionSampleDrawnDate,
		SecondaryPreTransfusionSampleDrawnTime,
		SecondaryPreTransfusionSampleQuantity,
		SecondaryPreTransfusionSampleHeldAt,
		SecondaryPreTransfusionSampleHeldDate,
		SecondaryPreTransfusionSampleHeldTime,
		SecondaryPreTransfusionSampleHeldTechnician,
		SecondaryPostMordemSampleTestSuitable,
		SecondaryPostMordemSampleLocation,
		SecondaryPostMordemSampleContact,
		SecondaryPostMordemSampleCollectionDate,
		SecondaryPostMordemSampleCollectionTime,
		SecondarySputumCharacteristics,
		SecondaryNOKAltPhone,
		SecondaryNOKLegal,
		SecondaryNOKAltContact,
		SecondaryNOKAltContactPhone,
		SecondaryNOKPostMortemAuthorization,
		SecondaryNOKPostMortemAuthorizationReminder,
		SecondaryCoronerCaseNumber,
		SecondaryCoronerCounty,
		SecondaryCoronerReleased,
		SecondaryCoronerReleasedStipulations,
		SecondaryAutopsy,
		SecondaryAutopsyDate,
		SecondaryAutopsyTime,
		SecondaryAutopsyLocation,
		SecondaryAutopsyBloodRequested,
		SecondaryAutopsyCopyRequested,
		SecondaryFuneralHomeSelected,
		SecondaryFuneralHomeName,
		SecondaryFuneralHomePhone,
		SecondaryFuneralHomeAddress,
		SecondaryFuneralHomeContact,
		SecondaryFuneralHomeNotified,
		SecondaryFuneralHomeMorgueCooled,
		SecondaryHoldOnBody,
		SecondaryHoldOnBodyTag,
		SecondaryBodyRefrigerationDate,
		SecondaryBodyRefrigerationTime,
		SecondaryBodyLocation,
		SecondaryBodyMedicalChartLocation,
		SecondaryBodyIDTagLocation,
		SecondaryBodyCoolingMethod,
		SecondaryUNOSNumber,
		SecondaryClientNumber,
		SecondaryCryolifeNumber,
		SecondaryMTFNumber,
		SecondaryLifeNetNumber,
		SecondaryFreeText,
		SecondaryHistorySubstanceAbuse,
		SecondarySubstanceAbuseDetail,
		SecondaryExtubationDate,
		SecondaryExtubationTime,
		SecondaryAutopsyReminderYN,
		SecondaryFHReminderYN,
		SecondaryBodyCareReminderYN,
		SecondaryWrapUpReminderYN,
		SecondaryNOKNotifiedBy,
		SecondaryNOKNotifiedDate,
		SecondaryNOKNotifiedTime,
		SecondaryNOKGender,
		SecondaryCODOther,
		SecondaryAutopsyLocationOther,
		SecondaryPatientHospitalPhone,
		SecondaryCoronerCase,
		SecondaryPatientABO,
		SecondaryPatientSuffix,
		SecondaryMDAttendingId,
		SecondaryAdditionalComments,
		SecondaryRhythm,
		SecondaryAdditionalMedications,
		SecondaryBodyHoldPlaced,
		SecondaryBodyHoldPlacedWith,
		SecondaryBodyFutureContact,
		SecondaryBodyHoldPhone,
		SecondaryBodyHoldInstructionsGiven,
		SecondarySteroid,
		SecondaryBodyHoldPlacedTime,
		LastStatEmployeeID,
		AuditLogTypeID,
		LastModified
	
	) 

VALUES 
	( 
		@CallID, 
		@SecondaryWhoAreWe, 
		@SecondaryNOKaware, 
		@SecondaryFamilyConsent, 
		@SecondaryFamilyInterested, 
		@SecondaryNOKatHospital, 
		@SecondaryEstTimeSinceLeft, 
		@SecondaryTimeLeftInMT, 
		@SecondaryNOKNextDest, 
		@SecondaryNOKETA, 
		@SecondaryPatientMiddleName, 
		@SecondaryPatientHeightFeet, 
		@SecondaryPatientHeightInches, 
		@SecondaryPatientBMICalc, 
		@SecondaryPatientTOD1, 
		@SecondaryPatientTOD2, 
		@SecondaryPatientDeathType1, 
		@SecondaryPatientDeathType2, 
		@SecondaryTriageHX, 
		@SecondaryCircumstanceOfDeath, 
		@SecondaryMedicalHistory, 
		@SecondaryAdmissionDiagnosis, 
		@SecondaryCOD, 
		@SecondaryCODSignatory, 
		@SecondaryCODTime, 
		@SecondaryCODSignedBy, 
		@SecondaryPatientVent, 
		@SecondaryIntubationDate, 
		@SecondaryIntubationTime, 
		@SecondaryBrainDeathDate, 
		@SecondaryBrainDeathTime, 
		@SecondaryDNRDate, 
		@SecondaryERORDeath, 
		@SecondaryEMSArrivalToPatientDate, 
		@SecondaryEMSArrivalToPatientTime, 
		@SecondaryEMSArrivalToHospitalDate, 
		@SecondaryEMSArrivalToHospitalTime, 
		@SecondaryPatientTerminal, 
		@SecondaryDeathWitnessed, 
		@SecondaryDeathWitnessedBy, 
		@SecondaryLSADate, 
		@SecondaryLSATime, 
		@SecondaryLSABy, 
		@SecondaryACLSProvided, 
		@SecondaryACLSProvidedTime, 
		@SecondaryGestationalAge, 
		@SecondaryParentName1, 
		@SecondaryParentName2, 
		@SecondaryBirthCBO, 
		@SecondaryActiveInfection, 
		@SecondaryActiveInfectionType, 
		@SecondaryFluidsGiven, 
		@SecondaryBloodLoss, 
		@SecondarySignOfInfection, 
		@SecondaryMedication, 
		@SecondaryAntibiotic, 
		@SecondaryPCPName, 
		@SecondaryPCPPhone, 
		@SecondaryMDAttending, 
		@SecondaryMDAttendingPhone, 
		@SecondaryPhysicalAppearance, 
		@SecondaryInternalBloodLossCC, 
		@SecondaryExternalBloodLossCC, 
		@SecondaryBloodProducts, 
		@SecondaryColloidsInfused, 
		@SecondaryCrystalloids, 
		@SecondaryPreTransfusionSampleRequired, 
		@SecondaryPreTransfusionSampleAvailable, 
		@SecondaryPreTransfusionSampleDrawnDate, 
		@SecondaryPreTransfusionSampleDrawnTime, 
		@SecondaryPreTransfusionSampleQuantity, 
		@SecondaryPreTransfusionSampleHeldAt, 
		@SecondaryPreTransfusionSampleHeldDate, 
		@SecondaryPreTransfusionSampleHeldTime, 
		@SecondaryPreTransfusionSampleHeldTechnician, 
		@SecondaryPostMordemSampleTestSuitable, 
		@SecondaryPostMordemSampleLocation, 
		@SecondaryPostMordemSampleContact, 
		@SecondaryPostMordemSampleCollectionDate, 
		@SecondaryPostMordemSampleCollectionTime, 
		@SecondarySputumCharacteristics, 
		@SecondaryNOKAltPhone, 
		@SecondaryNOKLegal, 
		@SecondaryNOKAltContact, 
		@SecondaryNOKAltContactPhone, 
		@SecondaryNOKPostMortemAuthorization, 
		@SecondaryNOKPostMortemAuthorizationReminder, 
		@SecondaryCoronerCaseNumber, 
		@SecondaryCoronerCounty, 
		@SecondaryCoronerReleased, 
		@SecondaryCoronerReleasedStipulations, 
		@SecondaryAutopsy, 
		@SecondaryAutopsyDate, 
		@SecondaryAutopsyTime, 
		@SecondaryAutopsyLocation, 
		@SecondaryAutopsyBloodRequested, 
		@SecondaryAutopsyCopyRequested, 
		@SecondaryFuneralHomeSelected, 
		@SecondaryFuneralHomeName, 
		@SecondaryFuneralHomePhone, 
		@SecondaryFuneralHomeAddress, 
		@SecondaryFuneralHomeContact, 
		@SecondaryFuneralHomeNotified, 
		@SecondaryFuneralHomeMorgueCooled, 
		@SecondaryHoldOnBody, 
		@SecondaryHoldOnBodyTag, 
		@SecondaryBodyRefrigerationDate, 
		@SecondaryBodyRefrigerationTime, 
		@SecondaryBodyLocation, 
		@SecondaryBodyMedicalChartLocation, 
		@SecondaryBodyIDTagLocation, 
		@SecondaryBodyCoolingMethod, 
		@SecondaryUNOSNumber, 
		@SecondaryClientNumber, 
		@SecondaryCryolifeNumber, 
		@SecondaryMTFNumber, 
		@SecondaryLifeNetNumber, 
		@SecondaryFreeText, 
		@SecondaryHistorySubstanceAbuse, 
		@SecondarySubstanceAbuseDetail, 
		@SecondaryExtubationDate, 
		@SecondaryExtubationTime, 
		@SecondaryAutopsyReminderYN, 
		@SecondaryFHReminderYN, 
		@SecondaryBodyCareReminderYN, 
		@SecondaryWrapUpReminderYN, 
		@SecondaryNOKNotifiedBy, 
		@SecondaryNOKNotifiedDate, 
		@SecondaryNOKNotifiedTime, 
		@SecondaryNOKGender, 
		@SecondaryCODOther, 
		@SecondaryAutopsyLocationOther, 
		@SecondaryPatientHospitalPhone, 
		@SecondaryCoronerCase, 
		@SecondaryPatientABO, 
		@SecondaryPatientSuffix, 
		@SecondaryMDAttendingId, 
		@SecondaryAdditionalComments, 
		@SecondaryRhythm, 
		@SecondaryAdditionalMedications, 
		@SecondaryBodyHoldPlaced, 
		@SecondaryBodyHoldPlacedWith, 
		@SecondaryBodyFutureContact, 
		@SecondaryBodyHoldPhone, 
		@SecondaryBodyHoldInstructionsGiven, 
		@SecondarySteroid, 
		@SecondaryBodyHoldPlacedTime, 
		@LastStatEmployeeID, 
		1, --@AuditLogTypeID 1 = Create
		GetDate() -- @LastModified 	
	) 

SELECT 
	CallID,
	SecondaryWhoAreWe,
	SecondaryNOKaware,
	SecondaryFamilyConsent,
	SecondaryFamilyInterested,
	SecondaryNOKatHospital,
	SecondaryEstTimeSinceLeft,
	SecondaryTimeLeftInMT,
	SecondaryNOKNextDest,
	SecondaryNOKETA,
	SecondaryPatientMiddleName,
	SecondaryPatientHeightFeet,
	SecondaryPatientHeightInches,
	SecondaryPatientBMICalc,
	SecondaryPatientTOD1,
	SecondaryPatientTOD2,
	SecondaryPatientDeathType1,
	SecondaryPatientDeathType2,
	SecondaryTriageHX,
	SecondaryCircumstanceOfDeath,
	SecondaryMedicalHistory,
	SecondaryAdmissionDiagnosis,
	SecondaryCOD,
	SecondaryCODSignatory,
	SecondaryCODTime,
	SecondaryCODSignedBy,
	SecondaryPatientVent,
	SecondaryIntubationDate,
	SecondaryIntubationTime,
	SecondaryBrainDeathDate,
	SecondaryBrainDeathTime,
	SecondaryDNRDate,
	SecondaryERORDeath,
	SecondaryEMSArrivalToPatientDate,
	SecondaryEMSArrivalToPatientTime,
	SecondaryEMSArrivalToHospitalDate,
	SecondaryEMSArrivalToHospitalTime,
	SecondaryPatientTerminal,
	SecondaryDeathWitnessed,
	SecondaryDeathWitnessedBy,
	SecondaryLSADate,
	SecondaryLSATime,
	SecondaryLSABy,
	SecondaryACLSProvided,
	SecondaryACLSProvidedTime,
	SecondaryGestationalAge,
	SecondaryParentName1,
	SecondaryParentName2,
	SecondaryBirthCBO,
	SecondaryActiveInfection,
	SecondaryActiveInfectionType,
	SecondaryFluidsGiven,
	SecondaryBloodLoss,
	SecondarySignOfInfection,
	SecondaryMedication,
	SecondaryAntibiotic,
	SecondaryPCPName,
	SecondaryPCPPhone,
	SecondaryMDAttending,
	SecondaryMDAttendingPhone,
	SecondaryPhysicalAppearance,
	SecondaryInternalBloodLossCC,
	SecondaryExternalBloodLossCC,
	SecondaryBloodProducts,
	SecondaryColloidsInfused,
	SecondaryCrystalloids,
	SecondaryPreTransfusionSampleRequired,
	SecondaryPreTransfusionSampleAvailable,
	SecondaryPreTransfusionSampleDrawnDate,
	SecondaryPreTransfusionSampleDrawnTime,
	SecondaryPreTransfusionSampleQuantity,
	SecondaryPreTransfusionSampleHeldAt,
	SecondaryPreTransfusionSampleHeldDate,
	SecondaryPreTransfusionSampleHeldTime,
	SecondaryPreTransfusionSampleHeldTechnician,
	SecondaryPostMordemSampleTestSuitable,
	SecondaryPostMordemSampleLocation,
	SecondaryPostMordemSampleContact,
	SecondaryPostMordemSampleCollectionDate,
	SecondaryPostMordemSampleCollectionTime,
	SecondarySputumCharacteristics,
	SecondaryNOKAltPhone,
	SecondaryNOKLegal,
	SecondaryNOKAltContact,
	SecondaryNOKAltContactPhone,
	SecondaryNOKPostMortemAuthorization,
	SecondaryNOKPostMortemAuthorizationReminder,
	SecondaryCoronerCaseNumber,
	SecondaryCoronerCounty,
	SecondaryCoronerReleased,
	SecondaryCoronerReleasedStipulations,
	SecondaryAutopsy,
	SecondaryAutopsyDate,
	SecondaryAutopsyTime,
	SecondaryAutopsyLocation,
	SecondaryAutopsyBloodRequested,
	SecondaryAutopsyCopyRequested,
	SecondaryFuneralHomeSelected,
	SecondaryFuneralHomeName,
	SecondaryFuneralHomePhone,
	SecondaryFuneralHomeAddress,
	SecondaryFuneralHomeContact,
	SecondaryFuneralHomeNotified,
	SecondaryFuneralHomeMorgueCooled,
	SecondaryHoldOnBody,
	SecondaryHoldOnBodyTag,
	SecondaryBodyRefrigerationDate,
	SecondaryBodyRefrigerationTime,
	SecondaryBodyLocation,
	SecondaryBodyMedicalChartLocation,
	SecondaryBodyIDTagLocation,
	SecondaryBodyCoolingMethod,
	SecondaryUNOSNumber,
	SecondaryClientNumber,
	SecondaryCryolifeNumber,
	SecondaryMTFNumber,
	SecondaryLifeNetNumber,
	SecondaryFreeText,
	SecondaryHistorySubstanceAbuse,
	SecondarySubstanceAbuseDetail,
	SecondaryExtubationDate,
	SecondaryExtubationTime,
	SecondaryAutopsyReminderYN,
	SecondaryFHReminderYN,
	SecondaryBodyCareReminderYN,
	SecondaryWrapUpReminderYN,
	SecondaryNOKNotifiedBy,
	SecondaryNOKNotifiedDate,
	SecondaryNOKNotifiedTime,
	SecondaryNOKGender,
	SecondaryCODOther,
	SecondaryAutopsyLocationOther,
	SecondaryPatientHospitalPhone,
	SecondaryCoronerCase,
	SecondaryPatientABO,
	SecondaryPatientSuffix,
	SecondaryMDAttendingId,
	SecondaryAdditionalComments,
	SecondaryRhythm,
	SecondaryAdditionalMedications,
	SecondaryBodyHoldPlaced,
	SecondaryBodyHoldPlacedWith,
	SecondaryBodyFutureContact,
	SecondaryBodyHoldPhone,
	SecondaryBodyHoldInstructionsGiven,
	SecondarySteroid,
	SecondaryBodyHoldPlacedTime
FROM 
	Secondary 
WHERE 
	CallID = @CallID




GO

GRANT EXEC ON InsertSecondary TO PUBLIC

GO
