IF EXISTS (Select * FROM sys.objects WHERE type = 'P' AND name = 'ReferralInsert')
BEGIN
	PRINT 'Dropping Procedure ReferralInsert';
	DROP Procedure ReferralInsert;
END
GO

PRINT 'Creating Procedure ReferralInsert';
GO
CREATE Procedure [dbo].[ReferralInsert]
(
		@ReferralID int = null output,
		@CallID int = null,
		@ReferralCallerPhoneID int = null,
		@ReferralCallerExtension varchar(10) = null,
		@ReferralCallerOrganizationID int = null,
		@ReferralCallerSubLocationID int = null,
		@ReferralCallerSubLocationLevel varchar(4) = null,
		@ReferralCallerPersonID int = null,
		@ReferralDonorName varchar(80) = null,
		@ReferralDonorRecNumber varchar(30) = null,
		@ReferralDonorRecNumberSearchable varchar(30) = NULL, 
		@ReferralDonorAge varchar(4) = null,
		@ReferralDonorAgeUnit varchar(10) = null,
		@ReferralDonorRaceID int = null,
		@ReferralDonorGender char(1) = null,
		@ReferralDonorWeight varchar(7) = null,
		@ReferralDonorAdmitDate smalldatetime = null,
		@ReferralDonorAdmitTime varchar(10) = null,
		@ReferralDonorDeathDate smalldatetime = null,
		@ReferralDonorDeathTime varchar(10) = null,
		@ReferralDonorLSADate smalldatetime = null,
		@ReferralDonorLSATime varchar(10) = null,
		@ReferralDonorCauseOfDeathID int = null,
		@ReferralDonorOnVentilator varchar(20) = null,
		@ReferralDonorDead varchar(4) = null,
		@ReferralTypeID int = null,
		@ReferralApproachTypeID int = null,
		@ReferralApproachedByPersonID int = null,
		@ReferralApproachNOK varchar(50) = null,
		@ReferralApproachRelation varchar(50) = null,
		@ReferralOrganAppropriateID int = null,
		@ReferralOrganApproachID int = null,
		@ReferralOrganConsentID int = null,
		@ReferralOrganConversionID int = null,
		@ReferralBoneAppropriateID int = null,
		@ReferralBoneApproachID int = null,
		@ReferralBoneConsentID int = null,
		@ReferralBoneConversionID int = null,
		@ReferralTissueAppropriateID int = null,
		@ReferralTissueApproachID int = null,
		@ReferralTissueConsentID int = null,
		@ReferralTissueConversionID int = null,
		@ReferralSkinAppropriateID int = null,
		@ReferralSkinApproachID int = null,
		@ReferralSkinConsentID int = null,
		@ReferralSkinConversionID int = null,
		@ReferralEyesTransAppropriateID int = null,
		@ReferralEyesTransApproachID int = null,
		@ReferralEyesTransConsentID int = null,
		@ReferralEyesTransConversionID int = null,
		@ReferralEyesRschAppropriateID int = null,
		@ReferralEyesRschApproachID int = null,
		@ReferralEyesRschConsentID int = null,
		@ReferralEyesRschConversionID int = null,
		@ReferralValvesAppropriateID int = null,
		@ReferralValvesApproachID int = null,
		@ReferralValvesConsentID int = null,
		@ReferralValvesConversionID int = null,
		@ReferralNotesCase varchar(400) = null,
		@ReferralNotesPrevious varchar(255) = null,
		@ReferralVerifiedOptions smallint = null,
		@ReferralCoronersCase smallint = null,
		@Inactive smallint = null,
		@ReferralCallerLevelID int = null,
		@LastModified datetime = null,
		@UnusedField1 smallint = null,
		@ReferralDonorFirstName varchar(40) = null,
		@ReferralDonorLastName varchar(40) = null,
		@ReferralOrganDispositionID int = null,
		@ReferralBoneDispositionID int = null,
		@ReferralTissueDispositionID int = null,
		@ReferralSkinDispositionID int = null,
		@ReferralValvesDispositionID int = null,
		@ReferralEyesDispositionID int = null,
		@ReferralRschDispositionID int = null,
		@ReferralAllTissueDispositionID int = null,
		@ReferralPronouncingMD int = null,
		@UnusedField3 int = null,
		@ReferralNOKPhone varchar(14) = null,
		@ReferralAttendingMD int = null,
		@ReferralGeneralConsent smallint = null,
		@ReferralNOKAddress varchar(255) = null,
		@ReferralCoronerName varchar(80) = null,
		@ReferralCoronerPhone varchar(14) = null,
		@ReferralCoronerOrganization varchar(80) = null,
		@ReferralCoronerNote varchar(255) = null,
		@ReferralApproachTime numeric(7,0) = null,
		@ReferralConsentTime numeric(7,0) = null,
		@Unused smalldatetime = null,
		@ReferralDOA smallint = null,
		@ReferralDOB datetime = null,
		@ReferralDonorSSN varchar(11) = null,
		@UpdatedFlag smallint = null,
		@ReferralExtubated varchar(15) = null,
		@DonorRegistryType smallint = null,
		@DonorRegId int = null,
		@DonorDMVId int = null,
		@DonorDMVTable varchar(255) = null,
		@DonorIntentDone smallint = null,
		@DonorFaxSent smallint = null,
		@DonorDSNID smallint = null,
		@ReferralDonorHeartBeat int = null,
		@ReferralCoronerOrgID int = null,
		@CurrentReferralTypeId int = null,
		@ReferralDonorBrainDeathDate smalldatetime = null,
		@ReferralDonorBrainDeathTime varchar(10) = null,
		@ReferralPronouncingMDPhone varchar(14) = null,
		@ReferralAttendingMDPhone varchar(14) = null,
		@ReferralDOB_ILB smallint = null,
		@ReferralDonorSpecificCOD varchar(250) = null,
		@ReferralDonorNameMI varchar(2) = null,
		@ReferralNOKID int = null,
		@ReferralQAReviewComplete smallint = null,
		@ReferralDCDPotential smallint = NULL,
		@ReferralPendingCase smallint = 0,
		@ReferralPendingCaseCoordinator smallint = NULL,
		@ReferralPendingCaseComment varchar(50) = NULL,
		@Hiv int = NULL,
		@Aids int = NULL,
		@HepB int = NULL,
		@HepC int = NULL,
		@Ivda int = NULL,
		@IdentityUnknown int = NULL,
		@AgeEstimated int = NULL,
		@WeightEstimated int = NULL,
		@PastMedicalHistory varchar(950) = NULL,
		@AdmittingDiagnosis varchar(950) = NULL,
		@LastStatEmployeeID int = null,
		@AuditLogTypeID int = null,
		@IsERferralCase bit = 0				
)
AS
/******************************************************************************
**	File: ReferralInsert.sql
**	Name: ReferralInsert
**	Desc: Inserts Referral Based on Id field 
**	Auth: Bret Knoll
**	Date: 1/7/2011
**	Called By: 
*******************************************************************************
**	Change History
*******************************************************************************
**	Date:			Author:					Description:
**	--------		--------				----------------------------------
**	1/7/2011		Bret Knoll			Initial Sproc Creation
**	05/28/2020		Mike Berenson		Added fields for e-referral
**	02/18/2020		Mike Berenson		Added missing parameter IsERferralCase
**	04/09/2021		Mike Berenson		Added fields from InsertReferral.sql
**	05/07/2021		Mike Berenson		Updated select to pass CallID with a named parameter
*******************************************************************************/

INSERT	Referral
	(
		CallID,
		ReferralCallerPhoneID,
		ReferralCallerExtension,
		ReferralCallerOrganizationID,
		ReferralCallerSubLocationID,
		ReferralCallerSubLocationLevel,
		ReferralCallerPersonID,
		ReferralDonorName,
		ReferralDonorRecNumber,
		ReferralDonorRecNumberSearchable,
		ReferralDonorAge,
		ReferralDonorAgeUnit,
		ReferralDonorRaceID,
		ReferralDonorGender,
		ReferralDonorWeight,
		ReferralDonorAdmitDate,
		ReferralDonorAdmitTime,
		ReferralDonorDeathDate,
		ReferralDonorDeathTime,
		ReferralDonorLSADate,
		ReferralDonorLSATime,
		ReferralDonorCauseOfDeathID,
		ReferralDonorOnVentilator,
		ReferralDonorDead,
		ReferralTypeID,
		ReferralApproachTypeID,
		ReferralApproachedByPersonID,
		ReferralApproachNOK,
		ReferralApproachRelation,
		ReferralOrganAppropriateID,
		ReferralOrganApproachID,
		ReferralOrganConsentID,
		ReferralOrganConversionID,
		ReferralBoneAppropriateID,
		ReferralBoneApproachID,
		ReferralBoneConsentID,
		ReferralBoneConversionID,
		ReferralTissueAppropriateID,
		ReferralTissueApproachID,
		ReferralTissueConsentID,
		ReferralTissueConversionID,
		ReferralSkinAppropriateID,
		ReferralSkinApproachID,
		ReferralSkinConsentID,
		ReferralSkinConversionID,
		ReferralEyesTransAppropriateID,
		ReferralEyesTransApproachID,
		ReferralEyesTransConsentID,
		ReferralEyesTransConversionID,
		ReferralEyesRschAppropriateID,
		ReferralEyesRschApproachID,
		ReferralEyesRschConsentID,
		ReferralEyesRschConversionID,
		ReferralValvesAppropriateID,
		ReferralValvesApproachID,
		ReferralValvesConsentID,
		ReferralValvesConversionID,
		ReferralNotesCase,
		ReferralNotesPrevious,
		ReferralVerifiedOptions,
		ReferralCoronersCase,
		Inactive,
		ReferralCallerLevelID,
		LastModified,
		UnusedField1,
		ReferralDonorFirstName,
		ReferralDonorLastName,
		ReferralOrganDispositionID,
		ReferralBoneDispositionID,
		ReferralTissueDispositionID,
		ReferralSkinDispositionID,
		ReferralValvesDispositionID,
		ReferralEyesDispositionID,
		ReferralRschDispositionID,
		ReferralAllTissueDispositionID,
		ReferralPronouncingMD,
		UnusedField3,
		ReferralNOKPhone,
		ReferralAttendingMD,
		ReferralGeneralConsent,
		ReferralNOKAddress,
		ReferralCoronerName,
		ReferralCoronerPhone,
		ReferralCoronerOrganization,
		ReferralCoronerNote,
		ReferralApproachTime,
		ReferralConsentTime,
		Unused,
		ReferralDOA,
		ReferralDOB,
		ReferralDonorSSN,
		UpdatedFlag,
		ReferralExtubated,
		DonorRegistryType,
		DonorRegId,
		DonorDMVId,
		DonorDMVTable,
		DonorIntentDone,
		DonorFaxSent,
		DonorDSNID,
		ReferralDonorHeartBeat,
		ReferralCoronerOrgID,
		CurrentReferralTypeId,
		ReferralDonorBrainDeathDate,
		ReferralDonorBrainDeathTime,
		ReferralPronouncingMDPhone,
		ReferralAttendingMDPhone,
		ReferralDOB_ILB,
		ReferralDonorSpecificCOD,
		ReferralDonorNameMI,
		ReferralNOKID,
		ReferralQAReviewComplete,			
		ReferralDCDPotential,
		ReferralPendingCase,
		ReferralPendingCaseCoordinator,
		ReferralPendingCaseComment,
		ReferralPendingCaseLastModified,	
		Hiv,
		Aids,
		HepB,
		HepC,
		Ivda,
		IdentityUnknown,
		AgeEstimated,
		WeightEstimated,
		PastMedicalHistory,
		AdmittingDiagnosis,
		LastStatEmployeeID,
		AuditLogTypeID,
		IsERferralCase
	)
VALUES
	(
		@CallID,
		@ReferralCallerPhoneID,
		@ReferralCallerExtension,
		@ReferralCallerOrganizationID,
		@ReferralCallerSubLocationID,
		@ReferralCallerSubLocationLevel,
		@ReferralCallerPersonID,
		@ReferralDonorName,
		@ReferralDonorRecNumber,
		@ReferralDonorRecNumberSearchable,
		@ReferralDonorAge,
		@ReferralDonorAgeUnit,
		@ReferralDonorRaceID,
		@ReferralDonorGender,
		@ReferralDonorWeight,
		@ReferralDonorAdmitDate,
		@ReferralDonorAdmitTime,
		@ReferralDonorDeathDate,
		@ReferralDonorDeathTime,
		@ReferralDonorLSADate,
		@ReferralDonorLSATime,
		@ReferralDonorCauseOfDeathID,
		@ReferralDonorOnVentilator,
		@ReferralDonorDead,
		@ReferralTypeID,
		@ReferralApproachTypeID,
		@ReferralApproachedByPersonID,
		@ReferralApproachNOK,
		@ReferralApproachRelation,
		@ReferralOrganAppropriateID,
		@ReferralOrganApproachID,
		@ReferralOrganConsentID,
		@ReferralOrganConversionID,
		@ReferralBoneAppropriateID,
		@ReferralBoneApproachID,
		@ReferralBoneConsentID,
		@ReferralBoneConversionID,
		@ReferralTissueAppropriateID,
		@ReferralTissueApproachID,
		@ReferralTissueConsentID,
		@ReferralTissueConversionID,
		@ReferralSkinAppropriateID,
		@ReferralSkinApproachID,
		@ReferralSkinConsentID,
		@ReferralSkinConversionID,
		@ReferralEyesTransAppropriateID,
		@ReferralEyesTransApproachID,
		@ReferralEyesTransConsentID,
		@ReferralEyesTransConversionID,
		@ReferralEyesRschAppropriateID,
		@ReferralEyesRschApproachID,
		@ReferralEyesRschConsentID,
		@ReferralEyesRschConversionID,
		@ReferralValvesAppropriateID,
		@ReferralValvesApproachID,
		@ReferralValvesConsentID,
		@ReferralValvesConversionID,
		@ReferralNotesCase,
		@ReferralNotesPrevious,
		@ReferralVerifiedOptions,
		@ReferralCoronersCase,
		@Inactive,
		@ReferralCallerLevelID,
		@LastModified,
		@UnusedField1,
		@ReferralDonorFirstName,
		@ReferralDonorLastName,
		@ReferralOrganDispositionID,
		@ReferralBoneDispositionID,
		@ReferralTissueDispositionID,
		@ReferralSkinDispositionID,
		@ReferralValvesDispositionID,
		@ReferralEyesDispositionID,
		@ReferralRschDispositionID,
		@ReferralAllTissueDispositionID,
		@ReferralPronouncingMD,
		@UnusedField3,
		@ReferralNOKPhone,
		@ReferralAttendingMD,
		@ReferralGeneralConsent,
		@ReferralNOKAddress,
		@ReferralCoronerName,
		@ReferralCoronerPhone,
		@ReferralCoronerOrganization,
		@ReferralCoronerNote,
		@ReferralApproachTime,
		@ReferralConsentTime,
		@Unused,
		@ReferralDOA,
		@ReferralDOB,
		@ReferralDonorSSN,
		@UpdatedFlag,
		@ReferralExtubated,
		@DonorRegistryType,
		@DonorRegId,
		@DonorDMVId,
		@DonorDMVTable,
		@DonorIntentDone,
		@DonorFaxSent,
		@DonorDSNID,
		@ReferralDonorHeartBeat,
		@ReferralCoronerOrgID,
		@CurrentReferralTypeId,
		@ReferralDonorBrainDeathDate,
		@ReferralDonorBrainDeathTime,
		@ReferralPronouncingMDPhone,
		@ReferralAttendingMDPhone,
		@ReferralDOB_ILB,
		@ReferralDonorSpecificCOD,
		@ReferralDonorNameMI,
		@ReferralNOKID,
		@ReferralQAReviewComplete,
		@ReferralDCDPotential,
		@ReferralPendingCase,
		@ReferralPendingCaseCoordinator, 
		@ReferralPendingCaseComment,	
		GETDATE(),	
		@Hiv,
		@Aids,
		@HepB,
		@HepC,
		@Ivda,
		@IdentityUnknown,
		@AgeEstimated,
		@WeightEstimated,
		@PastMedicalHistory,
		@AdmittingDiagnosis,
		@LastStatEmployeeID,
		ISNULL(@AuditLogTypeID, 1), /* insert */
		@IsERferralCase
	);

SET @ReferralID = SCOPE_IDENTITY();

EXEC ReferralSelect @CallID = @CallID;
GO

GRANT EXEC ON ReferralInsert TO PUBLIC
GO
