

IF EXISTS (Select * FROM sys.objects WHERE type = 'P' AND name = 'ServiceLevelUpdate')
	BEGIN
		PRINT 'Dropping Procedure ServiceLevelUpdate'
		DROP Procedure ServiceLevelUpdate
	END
GO

PRINT 'Creating Procedure ServiceLevelUpdate'
GO
CREATE Procedure ServiceLevelUpdate
(
		@ServiceLevelID int = null output,
		@ServiceLevelGroupName varchar(80) = null,
		@ServiceLevelTriageLevel smallint = null,
		@ServiceLevelOTEMROLevel smallint = null,
		@ServiceLevelTEMROLevel smallint = null,
		@ServiceLevelEMROLevel smallint = null,
		@ServiceLevelLastName smallint = null,
		@ServiceLevelFirstName smallint = null,
		@ServiceLevelRecNum smallint = null,
		@ServiceLevelSSN smallint = null,
		@ServiceLevelGender smallint = null,
		@ServiceLevelAge smallint = null,
		@ServiceLevelWeight smallint = null,
		@ServiceLevelWeightAgeLimit numeric(3,0) = null,
		@ServiceLevelRace smallint = null,
		@ServiceLevelVent smallint = null,
		@ServiceLevelPrevVentClass smallint = null,
		@ServiceLevelDead smallint = null,
		@ServiceLevelDeathDate smallint = null,
		@ServiceLevelDeathTime smallint = null,
		@ServiceLevelAdmitDate smallint = null,
		@ServiceLevelAdmitTime smallint = null,
		@ServiceLevelCOD smallint = null,
		@ServiceLevelDOB smallint = null,
		@ServiceLevelDOA smallint = null,
		@ServiceLevelCoroner smallint = null,
		@ServiceLevelAttendingMD smallint = null,
		@ServiceLevelPronouncingMD smallint = null,
		@ServiceLevelApproachMethod smallint = null,
		@ServiceLevelApproachBy smallint = null,
		@ServiceLevelApproachOTEPrompt smallint = null,
		@ServiceLevelApproachTEPrompt smallint = null,
		@ServiceLevelApproachEPrompt smallint = null,
		@ServiceLevelApproachROPrompt smallint = null,
		@ServiceLevelNOK smallint = null,
		@ServiceLevelRelation smallint = null,
		@ServiceLevelNOKPhone smallint = null,
		@ServiceLevelNOKAddress smallint = null,
		@ServiceLevelAppropriateOrgan smallint = null,
		@ServiceLevelAppropriateBone smallint = null,
		@ServiceLevelAppropriateTissue smallint = null,
		@ServiceLevelAppropriateSkin smallint = null,
		@ServiceLevelAppropriateValves smallint = null,
		@ServiceLevelAppropriateEyes smallint = null,
		@ServiceLevelAppropriateRsch smallint = null,
		@ServiceLevelApproachOrgan smallint = null,
		@ServiceLevelApproachBone smallint = null,
		@ServiceLevelApproachTissue smallint = null,
		@ServiceLevelApproachSkin smallint = null,
		@ServiceLevelApproachValves smallint = null,
		@ServiceLevelApproachEyes smallint = null,
		@ServiceLevelApproachRsch smallint = null,
		@ServiceLevelConsentOrgan smallint = null,
		@ServiceLevelConsentBone smallint = null,
		@ServiceLevelConsentTissue smallint = null,
		@ServiceLevelConsentSkin smallint = null,
		@ServiceLevelConsentValves smallint = null,
		@ServiceLevelConsentEyes smallint = null,
		@ServiceLevelConsentRsch smallint = null,
		@ServiceLevelRecoveryOrgan smallint = null,
		@ServiceLevelRecoveryBone smallint = null,
		@ServiceLevelRecoveryTissue smallint = null,
		@ServiceLevelRecoverySkin smallint = null,
		@ServiceLevelRecoveryValves smallint = null,
		@ServiceLevelRecoveryEyes smallint = null,
		@ServiceLevelRecoveryRsch smallint = null,
		@LastModified datetime = null,
		@ServiceLevelExcludePrevVent smallint = null,
		@ServiceLevelCheckRegistry smallint = null,
		@ServiceLevelDonorIntentFaxYN smallint = null,
		@ServiceLevelDonorIntentNurseScript varchar(255) = null,
		@ServiceLevelDonorIntentOrganizationId int = null,
		@ServiceLevelDonorIntentOrganization varchar(50) = null,
		@ServiceLevelDonorIntentFaxId int = null,
		@ServiceLevelDonorIntentFax varchar(50) = null,
		@ServiceLevelDonorIntentPersonId int = null,
		@ServiceLevelDonorIntentPerson varchar(50) = null,
		@ServiceLevelDonorIntentRetries int = null,
		@ServiceLevelDonorIntentDocumentName varchar(50) = null,
		@ServiceLevelRegCheckRegistry smallint = null,
		@ServiceLevelStatus smallint = null,
		@WorkingStatusUpdatedFlag smallint = null,
		@WorkingServiceLevelId int = null,
		@ServiceLevelEyeCareReminder varchar(255) = null,
		@ServiceLevelHeartBeat smallint = null,
		@ServiceLevelNOKConsent smallint = null,
		@ServiceLevelNOKRegistration smallint = null,
		@ServiceLevelEmailDisposition smallint = null,
		@ServiceLevelDonorBrainDeathDate smallint = null,
		@ServiceLevelDonorBrainDeathTime smallint = null,
		@ServiceLevelPronouncingMDPhone smallint = null,
		@ServiceLevelAttendingMDPhone smallint = null,
		@ServiceLevelDOB_ILB smallint = null,
		@ServiceLevelDonorNameMI smallint = null,
		@ServiceLevelDonorSpecificCOD smallint = null,
		@ServiceLevelApproachLevel int = null,
		@ServiceLevelDisableASPSave int = null,
		@ServiceLevelAlwaysPopRegistry smallint = null,
		@ServiceLevelBillSecondaryManualEnable smallint = null,
		@ServiceLevelBillFamilyApproachManualEnable smallint = null,
		@ServiceLevelBillMedSocManualEnable smallint = null,
		@ServiceLevelVerifyWeight smallint = null,
		@ServiceLevelVerifySex smallint = null,
		@ServiceLevelBillApproachOnly smallint = null,
		@ServiceLevelPNEAllowSaveWithoutContactRequired smallint = null
							
)
AS
/******************************************************************************
**	File: ServiceLevelUpdate.sql
**	Name: ServiceLevelUpdate
**	Desc: Updates ServiceLevel Based on Id field 
**	Auth: Bret Knoll
**	Date: 12/14/2009
**	Called By: 
*******************************************************************************
**	Change History
*******************************************************************************
**	Date:			Author:					Description:
**	--------		--------				----------------------------------
**	12/14/2009		Bret Knoll			Initial Sproc Creation
**	07/12/2010		ccarroll			added this note for development build (GenerateSQL)
**	09/13/2011		ccarroll			Added ServiceLevelPNEAllowSaveWithoutContactRequired CCRST151
*******************************************************************************/

UPDATE
	dbo.ServiceLevel 	
SET 
		ServiceLevelGroupName = @ServiceLevelGroupName,
		ServiceLevelTriageLevel = @ServiceLevelTriageLevel,
		ServiceLevelOTEMROLevel = @ServiceLevelOTEMROLevel,
		ServiceLevelTEMROLevel = @ServiceLevelTEMROLevel,
		ServiceLevelEMROLevel = @ServiceLevelEMROLevel,
		ServiceLevelLastName = @ServiceLevelLastName,
		ServiceLevelFirstName = @ServiceLevelFirstName,
		ServiceLevelRecNum = @ServiceLevelRecNum,
		ServiceLevelSSN = @ServiceLevelSSN,
		ServiceLevelGender = @ServiceLevelGender,
		ServiceLevelAge = @ServiceLevelAge,
		ServiceLevelWeight = @ServiceLevelWeight,
		ServiceLevelWeightAgeLimit = @ServiceLevelWeightAgeLimit,
		ServiceLevelRace = @ServiceLevelRace,
		ServiceLevelVent = @ServiceLevelVent,
		ServiceLevelPrevVentClass = @ServiceLevelPrevVentClass,
		ServiceLevelDead = @ServiceLevelDead,
		ServiceLevelDeathDate = @ServiceLevelDeathDate,
		ServiceLevelDeathTime = @ServiceLevelDeathTime,
		ServiceLevelAdmitDate = @ServiceLevelAdmitDate,
		ServiceLevelAdmitTime = @ServiceLevelAdmitTime,
		ServiceLevelCOD = @ServiceLevelCOD,
		ServiceLevelDOB = @ServiceLevelDOB,
		ServiceLevelDOA = @ServiceLevelDOA,
		ServiceLevelCoroner = @ServiceLevelCoroner,
		ServiceLevelAttendingMD = @ServiceLevelAttendingMD,
		ServiceLevelPronouncingMD = @ServiceLevelPronouncingMD,
		ServiceLevelApproachMethod = @ServiceLevelApproachMethod,
		ServiceLevelApproachBy = @ServiceLevelApproachBy,
		ServiceLevelApproachOTEPrompt = @ServiceLevelApproachOTEPrompt,
		ServiceLevelApproachTEPrompt = @ServiceLevelApproachTEPrompt,
		ServiceLevelApproachEPrompt = @ServiceLevelApproachEPrompt,
		ServiceLevelApproachROPrompt = @ServiceLevelApproachROPrompt,
		ServiceLevelNOK = @ServiceLevelNOK,
		ServiceLevelRelation = @ServiceLevelRelation,
		ServiceLevelNOKPhone = @ServiceLevelNOKPhone,
		ServiceLevelNOKAddress = @ServiceLevelNOKAddress,
		ServiceLevelAppropriateOrgan = @ServiceLevelAppropriateOrgan,
		ServiceLevelAppropriateBone = @ServiceLevelAppropriateBone,
		ServiceLevelAppropriateTissue = @ServiceLevelAppropriateTissue,
		ServiceLevelAppropriateSkin = @ServiceLevelAppropriateSkin,
		ServiceLevelAppropriateValves = @ServiceLevelAppropriateValves,
		ServiceLevelAppropriateEyes = @ServiceLevelAppropriateEyes,
		ServiceLevelAppropriateRsch = @ServiceLevelAppropriateRsch,
		ServiceLevelApproachOrgan = @ServiceLevelApproachOrgan,
		ServiceLevelApproachBone = @ServiceLevelApproachBone,
		ServiceLevelApproachTissue = @ServiceLevelApproachTissue,
		ServiceLevelApproachSkin = @ServiceLevelApproachSkin,
		ServiceLevelApproachValves = @ServiceLevelApproachValves,
		ServiceLevelApproachEyes = @ServiceLevelApproachEyes,
		ServiceLevelApproachRsch = @ServiceLevelApproachRsch,
		ServiceLevelConsentOrgan = @ServiceLevelConsentOrgan,
		ServiceLevelConsentBone = @ServiceLevelConsentBone,
		ServiceLevelConsentTissue = @ServiceLevelConsentTissue,
		ServiceLevelConsentSkin = @ServiceLevelConsentSkin,
		ServiceLevelConsentValves = @ServiceLevelConsentValves,
		ServiceLevelConsentEyes = @ServiceLevelConsentEyes,
		ServiceLevelConsentRsch = @ServiceLevelConsentRsch,
		ServiceLevelRecoveryOrgan = @ServiceLevelRecoveryOrgan,
		ServiceLevelRecoveryBone = @ServiceLevelRecoveryBone,
		ServiceLevelRecoveryTissue = @ServiceLevelRecoveryTissue,
		ServiceLevelRecoverySkin = @ServiceLevelRecoverySkin,
		ServiceLevelRecoveryValves = @ServiceLevelRecoveryValves,
		ServiceLevelRecoveryEyes = @ServiceLevelRecoveryEyes,
		ServiceLevelRecoveryRsch = @ServiceLevelRecoveryRsch,
		LastModified = GetDate(),
		ServiceLevelExcludePrevVent = @ServiceLevelExcludePrevVent,
		ServiceLevelCheckRegistry = @ServiceLevelCheckRegistry,
		ServiceLevelDonorIntentFaxYN = @ServiceLevelDonorIntentFaxYN,
		ServiceLevelDonorIntentNurseScript = @ServiceLevelDonorIntentNurseScript,
		ServiceLevelDonorIntentOrganizationId = @ServiceLevelDonorIntentOrganizationId,
		ServiceLevelDonorIntentFaxId = @ServiceLevelDonorIntentFaxId,
		ServiceLevelDonorIntentPersonId = @ServiceLevelDonorIntentPersonId,
		ServiceLevelDonorIntentRetries = @ServiceLevelDonorIntentRetries,
		ServiceLevelDonorIntentDocumentName = @ServiceLevelDonorIntentDocumentName,
		ServiceLevelRegCheckRegistry = @ServiceLevelRegCheckRegistry,
		ServiceLevelStatus = @ServiceLevelStatus,
		WorkingStatusUpdatedFlag = @WorkingStatusUpdatedFlag,
		WorkingServiceLevelId = @WorkingServiceLevelId,
		ServiceLevelEyeCareReminder = @ServiceLevelEyeCareReminder,
		ServiceLevelHeartBeat = @ServiceLevelHeartBeat,
		ServiceLevelNOKConsent = @ServiceLevelNOKConsent,
		ServiceLevelNOKRegistration = @ServiceLevelNOKRegistration,
		ServiceLevelEmailDisposition = @ServiceLevelEmailDisposition,
		ServiceLevelDonorBrainDeathDate = @ServiceLevelDonorBrainDeathDate,
		ServiceLevelDonorBrainDeathTime = @ServiceLevelDonorBrainDeathTime,
		ServiceLevelPronouncingMDPhone = @ServiceLevelPronouncingMDPhone,
		ServiceLevelAttendingMDPhone = @ServiceLevelAttendingMDPhone,
		ServiceLevelDOB_ILB = @ServiceLevelDOB_ILB,
		ServiceLevelDonorNameMI = @ServiceLevelDonorNameMI,
		ServiceLevelDonorSpecificCOD = @ServiceLevelDonorSpecificCOD,
		ServiceLevelApproachLevel = @ServiceLevelApproachLevel,
		ServiceLevelDisableASPSave = @ServiceLevelDisableASPSave,
		ServiceLevelAlwaysPopRegistry = @ServiceLevelAlwaysPopRegistry,
		ServiceLevelBillSecondaryManualEnable = @ServiceLevelBillSecondaryManualEnable,
		ServiceLevelBillFamilyApproachManualEnable = @ServiceLevelBillFamilyApproachManualEnable,
		ServiceLevelBillMedSocManualEnable = @ServiceLevelBillMedSocManualEnable,
		ServiceLevelVerifyWeight = @ServiceLevelVerifyWeight,
		ServiceLevelVerifySex = @ServiceLevelVerifySex,
		ServiceLevelBillApproachOnly = @ServiceLevelBillApproachOnly,
		ServiceLevelPNEAllowSaveWithoutContactRequired = @ServiceLevelPNEAllowSaveWithoutContactRequired
WHERE 
	ServiceLevelID = @ServiceLevelID 				

GO

GRANT EXEC ON ServiceLevelUpdate TO PUBLIC
GO
