

IF EXISTS (Select * FROM sys.objects WHERE type = 'P' AND name = 'ServiceLevelInsert')
	BEGIN
		PRINT 'Dropping Procedure ServiceLevelInsert'
		DROP Procedure ServiceLevelInsert
	END
GO

PRINT 'Creating Procedure ServiceLevelInsert'
GO
CREATE Procedure ServiceLevelInsert
(
		@ServiceLevelID int = null output,
		@ServiceLevelGroupName varchar(80) = null,
		@ServiceLevelTriageLevel smallint = null,
		@ServiceLevelOTEMROLevel smallint = null,
		@ServiceLevelTEMROLevel smallint = null,
		@ServiceLevelEMROLevel smallint = null,
		@ServiceLevelLastName smallint = null,
		@ServiceLevelFirstName smallint = null,
		@ServiceLevelRecNum smallint = null,
		@ServiceLevelSSN smallint = null,
		@ServiceLevelGender smallint = null,
		@ServiceLevelAge smallint = null,
		@ServiceLevelWeight smallint = null,
		@ServiceLevelWeightAgeLimit numeric(3,0) = null,
		@ServiceLevelRace smallint = null,
		@ServiceLevelVent smallint = null,
		@ServiceLevelPrevVentClass smallint = null,
		@ServiceLevelDead smallint = null,
		@ServiceLevelDeathDate smallint = null,
		@ServiceLevelDeathTime smallint = null,
		@ServiceLevelAdmitDate smallint = null,
		@ServiceLevelAdmitTime smallint = null,
		@ServiceLevelCOD smallint = null,
		@ServiceLevelDOB smallint = null,
		@ServiceLevelDOA smallint = null,
		@ServiceLevelCoroner smallint = null,
		@ServiceLevelAttendingMD smallint = null,
		@ServiceLevelPronouncingMD smallint = null,
		@ServiceLevelApproachMethod smallint = null,
		@ServiceLevelApproachBy smallint = null,
		@ServiceLevelApproachOTEPrompt smallint = null,
		@ServiceLevelApproachTEPrompt smallint = null,
		@ServiceLevelApproachEPrompt smallint = null,
		@ServiceLevelApproachROPrompt smallint = null,
		@ServiceLevelNOK smallint = null,
		@ServiceLevelRelation smallint = null,
		@ServiceLevelNOKPhone smallint = null,
		@ServiceLevelNOKAddress smallint = null,
		@ServiceLevelAppropriateOrgan smallint = null,
		@ServiceLevelAppropriateBone smallint = null,
		@ServiceLevelAppropriateTissue smallint = null,
		@ServiceLevelAppropriateSkin smallint = null,
		@ServiceLevelAppropriateValves smallint = null,
		@ServiceLevelAppropriateEyes smallint = null,
		@ServiceLevelAppropriateRsch smallint = null,
		@ServiceLevelApproachOrgan smallint = null,
		@ServiceLevelApproachBone smallint = null,
		@ServiceLevelApproachTissue smallint = null,
		@ServiceLevelApproachSkin smallint = null,
		@ServiceLevelApproachValves smallint = null,
		@ServiceLevelApproachEyes smallint = null,
		@ServiceLevelApproachRsch smallint = null,
		@ServiceLevelConsentOrgan smallint = null,
		@ServiceLevelConsentBone smallint = null,
		@ServiceLevelConsentTissue smallint = null,
		@ServiceLevelConsentSkin smallint = null,
		@ServiceLevelConsentValves smallint = null,
		@ServiceLevelConsentEyes smallint = null,
		@ServiceLevelConsentRsch smallint = null,
		@ServiceLevelRecoveryOrgan smallint = null,
		@ServiceLevelRecoveryBone smallint = null,
		@ServiceLevelRecoveryTissue smallint = null,
		@ServiceLevelRecoverySkin smallint = null,
		@ServiceLevelRecoveryValves smallint = null,
		@ServiceLevelRecoveryEyes smallint = null,
		@ServiceLevelRecoveryRsch smallint = null,
		@LastModified datetime = null,
		@ServiceLevelExcludePrevVent smallint = null,
		@ServiceLevelCheckRegistry smallint = null,
		@ServiceLevelDonorIntentFaxYN smallint = null,
		@ServiceLevelDonorIntentNurseScript varchar(255) = null,
		@ServiceLevelDonorIntentOrganizationId int = null,
		@ServiceLevelDonorIntentOrganization varchar(50) = null,
		@ServiceLevelDonorIntentFaxId int = null,
		@ServiceLevelDonorIntentFax varchar(50) = null,
		@ServiceLevelDonorIntentPersonId int = null,
		@ServiceLevelDonorIntentPerson varchar(50) = null,
		@ServiceLevelDonorIntentRetries int = null,
		@ServiceLevelDonorIntentDocumentName varchar(50) = null,
		@ServiceLevelRegCheckRegistry smallint = null,
		@ServiceLevelStatus smallint = null,
		@WorkingStatusUpdatedFlag smallint = null,
		@WorkingServiceLevelId int = null,
		@ServiceLevelEyeCareReminder varchar(255) = null,
		@ServiceLevelHeartBeat smallint = null,
		@ServiceLevelNOKConsent smallint = null,
		@ServiceLevelNOKRegistration smallint = null,
		@ServiceLevelEmailDisposition smallint = null,
		@ServiceLevelDonorBrainDeathDate smallint = null,
		@ServiceLevelDonorBrainDeathTime smallint = null,
		@ServiceLevelPronouncingMDPhone smallint = null,
		@ServiceLevelAttendingMDPhone smallint = null,
		@ServiceLevelDOB_ILB smallint = null,
		@ServiceLevelDonorNameMI smallint = null,
		@ServiceLevelDonorSpecificCOD smallint = null,
		@ServiceLevelApproachLevel int = null,
		@ServiceLevelDisableASPSave int = null,
		@ServiceLevelAlwaysPopRegistry smallint = null,
		@ServiceLevelBillSecondaryManualEnable smallint = null,
		@ServiceLevelBillFamilyApproachManualEnable smallint = null,
		@ServiceLevelBillMedSocManualEnable smallint = null,
		@ServiceLevelVerifyWeight smallint = null,
		@ServiceLevelVerifySex smallint = null,
		@ServiceLevelBillApproachOnly smallint = null,
		@ServiceLevelPNEAllowSaveWithoutContactRequired smallint = null					
)
AS
/******************************************************************************
**	File: ServiceLevelInsert.sql
**	Name: ServiceLevelInsert
**	Desc: Inserts ServiceLevel Based on Id field 
**	Auth: Bret Knoll
**	Date: 12/14/2009
**	Called By: 
*******************************************************************************
**	Change History
*******************************************************************************
**	Date:			Author:					Description:
**	--------		--------				----------------------------------
**	12/14/2009		Bret Knoll			Initial Sproc Creation
**	07/12/2010		ccarroll			added this note for development build (GenerateSQL)
**  09/13/2011		ccarroll			Added Servicelevel for PNEAllowSaveWithoutContactRequired CCRST151
*******************************************************************************/

INSERT	ServiceLevel
	(
		ServiceLevelGroupName,
		ServiceLevelTriageLevel,
		ServiceLevelOTEMROLevel,
		ServiceLevelTEMROLevel,
		ServiceLevelEMROLevel,
		ServiceLevelLastName,
		ServiceLevelFirstName,
		ServiceLevelRecNum,
		ServiceLevelSSN,
		ServiceLevelGender,
		ServiceLevelAge,
		ServiceLevelWeight,
		ServiceLevelWeightAgeLimit,
		ServiceLevelRace,
		ServiceLevelVent,
		ServiceLevelPrevVentClass,
		ServiceLevelDead,
		ServiceLevelDeathDate,
		ServiceLevelDeathTime,
		ServiceLevelAdmitDate,
		ServiceLevelAdmitTime,
		ServiceLevelCOD,
		ServiceLevelDOB,
		ServiceLevelDOA,
		ServiceLevelCoroner,
		ServiceLevelAttendingMD,
		ServiceLevelPronouncingMD,
		ServiceLevelApproachMethod,
		ServiceLevelApproachBy,
		ServiceLevelApproachOTEPrompt,
		ServiceLevelApproachTEPrompt,
		ServiceLevelApproachEPrompt,
		ServiceLevelApproachROPrompt,
		ServiceLevelNOK,
		ServiceLevelRelation,
		ServiceLevelNOKPhone,
		ServiceLevelNOKAddress,
		ServiceLevelAppropriateOrgan,
		ServiceLevelAppropriateBone,
		ServiceLevelAppropriateTissue,
		ServiceLevelAppropriateSkin,
		ServiceLevelAppropriateValves,
		ServiceLevelAppropriateEyes,
		ServiceLevelAppropriateRsch,
		ServiceLevelApproachOrgan,
		ServiceLevelApproachBone,
		ServiceLevelApproachTissue,
		ServiceLevelApproachSkin,
		ServiceLevelApproachValves,
		ServiceLevelApproachEyes,
		ServiceLevelApproachRsch,
		ServiceLevelConsentOrgan,
		ServiceLevelConsentBone,
		ServiceLevelConsentTissue,
		ServiceLevelConsentSkin,
		ServiceLevelConsentValves,
		ServiceLevelConsentEyes,
		ServiceLevelConsentRsch,
		ServiceLevelRecoveryOrgan,
		ServiceLevelRecoveryBone,
		ServiceLevelRecoveryTissue,
		ServiceLevelRecoverySkin,
		ServiceLevelRecoveryValves,
		ServiceLevelRecoveryEyes,
		ServiceLevelRecoveryRsch,
		LastModified,
		ServiceLevelExcludePrevVent,
		ServiceLevelCheckRegistry,
		ServiceLevelDonorIntentFaxYN,
		ServiceLevelDonorIntentNurseScript,
		ServiceLevelDonorIntentOrganizationId,
		ServiceLevelDonorIntentFaxId,
		ServiceLevelDonorIntentPersonId,
		ServiceLevelDonorIntentRetries,
		ServiceLevelDonorIntentDocumentName,
		ServiceLevelRegCheckRegistry,
		ServiceLevelStatus,
		WorkingStatusUpdatedFlag,
		WorkingServiceLevelId,
		ServiceLevelEyeCareReminder,
		ServiceLevelHeartBeat,
		ServiceLevelNOKConsent,
		ServiceLevelNOKRegistration,
		ServiceLevelEmailDisposition,
		ServiceLevelDonorBrainDeathDate,
		ServiceLevelDonorBrainDeathTime,
		ServiceLevelPronouncingMDPhone,
		ServiceLevelAttendingMDPhone,
		ServiceLevelDOB_ILB,
		ServiceLevelDonorNameMI,
		ServiceLevelDonorSpecificCOD,
		ServiceLevelApproachLevel,
		ServiceLevelDisableASPSave,
		ServiceLevelAlwaysPopRegistry,
		ServiceLevelBillSecondaryManualEnable,
		ServiceLevelBillFamilyApproachManualEnable,
		ServiceLevelBillMedSocManualEnable,
		ServiceLevelVerifyWeight,
		ServiceLevelVerifySex,
		ServiceLevelBillApproachOnly,
		ServiceLevelPNEAllowSaveWithoutContactRequired
	)
VALUES
	(
		@ServiceLevelGroupName,
		@ServiceLevelTriageLevel,
		@ServiceLevelOTEMROLevel,
		@ServiceLevelTEMROLevel,
		@ServiceLevelEMROLevel,
		@ServiceLevelLastName,
		@ServiceLevelFirstName,
		@ServiceLevelRecNum,
		@ServiceLevelSSN,
		@ServiceLevelGender,
		@ServiceLevelAge,
		@ServiceLevelWeight,
		@ServiceLevelWeightAgeLimit,
		@ServiceLevelRace,
		@ServiceLevelVent,
		@ServiceLevelPrevVentClass,
		@ServiceLevelDead,
		@ServiceLevelDeathDate,
		@ServiceLevelDeathTime,
		@ServiceLevelAdmitDate,
		@ServiceLevelAdmitTime,
		@ServiceLevelCOD,
		@ServiceLevelDOB,
		@ServiceLevelDOA,
		@ServiceLevelCoroner,
		@ServiceLevelAttendingMD,
		@ServiceLevelPronouncingMD,
		@ServiceLevelApproachMethod,
		@ServiceLevelApproachBy,
		@ServiceLevelApproachOTEPrompt,
		@ServiceLevelApproachTEPrompt,
		@ServiceLevelApproachEPrompt,
		@ServiceLevelApproachROPrompt,
		@ServiceLevelNOK,
		@ServiceLevelRelation,
		@ServiceLevelNOKPhone,
		@ServiceLevelNOKAddress,
		@ServiceLevelAppropriateOrgan,
		@ServiceLevelAppropriateBone,
		@ServiceLevelAppropriateTissue,
		@ServiceLevelAppropriateSkin,
		@ServiceLevelAppropriateValves,
		@ServiceLevelAppropriateEyes,
		@ServiceLevelAppropriateRsch,
		@ServiceLevelApproachOrgan,
		@ServiceLevelApproachBone,
		@ServiceLevelApproachTissue,
		@ServiceLevelApproachSkin,
		@ServiceLevelApproachValves,
		@ServiceLevelApproachEyes,
		@ServiceLevelApproachRsch,
		@ServiceLevelConsentOrgan,
		@ServiceLevelConsentBone,
		@ServiceLevelConsentTissue,
		@ServiceLevelConsentSkin,
		@ServiceLevelConsentValves,
		@ServiceLevelConsentEyes,
		@ServiceLevelConsentRsch,
		@ServiceLevelRecoveryOrgan,
		@ServiceLevelRecoveryBone,
		@ServiceLevelRecoveryTissue,
		@ServiceLevelRecoverySkin,
		@ServiceLevelRecoveryValves,
		@ServiceLevelRecoveryEyes,
		@ServiceLevelRecoveryRsch,
		@LastModified,
		@ServiceLevelExcludePrevVent,
		@ServiceLevelCheckRegistry,
		@ServiceLevelDonorIntentFaxYN,
		@ServiceLevelDonorIntentNurseScript,
		@ServiceLevelDonorIntentOrganizationId,
		@ServiceLevelDonorIntentFaxId,
		@ServiceLevelDonorIntentPersonId,
		@ServiceLevelDonorIntentRetries,
		@ServiceLevelDonorIntentDocumentName,
		@ServiceLevelRegCheckRegistry,
		@ServiceLevelStatus,
		@WorkingStatusUpdatedFlag,
		@WorkingServiceLevelId,
		@ServiceLevelEyeCareReminder,
		@ServiceLevelHeartBeat,
		@ServiceLevelNOKConsent,
		@ServiceLevelNOKRegistration,
		@ServiceLevelEmailDisposition,
		@ServiceLevelDonorBrainDeathDate,
		@ServiceLevelDonorBrainDeathTime,
		@ServiceLevelPronouncingMDPhone,
		@ServiceLevelAttendingMDPhone,
		@ServiceLevelDOB_ILB,
		@ServiceLevelDonorNameMI,
		@ServiceLevelDonorSpecificCOD,
		@ServiceLevelApproachLevel,
		@ServiceLevelDisableASPSave,
		@ServiceLevelAlwaysPopRegistry,
		@ServiceLevelBillSecondaryManualEnable,
		@ServiceLevelBillFamilyApproachManualEnable,
		@ServiceLevelBillMedSocManualEnable,
		@ServiceLevelVerifyWeight,
		@ServiceLevelVerifySex,
		@ServiceLevelBillApproachOnly,
		@ServiceLevelPNEAllowSaveWithoutContactRequired
	)

SET @ServiceLevelID = SCOPE_IDENTITY()

EXEC ServiceLevelSelect @ServiceLevelID

GO

GRANT EXEC ON ServiceLevelInsert TO PUBLIC
GO
