using System.Collections.ObjectModel;

#nullable disable

namespace Statline.StatTrac.Domain.Referrals;

/// <dev>
/// This a "read" model, so it looks anemic.
/// </dev>
public sealed class ReferralDetails
{
    internal ReferralDetails() { }
    public string ApproachBy { get; private set; }
    public string ApproachTypeName { get; private set; }
    public string AttendingPhysician { get; private set; }
    public DateTimeOffset? CallDateTime { get; private set; }
    public string Caller { get; private set; }
    public string CallerOrganizationUnit { get; private set; }
    public string CallerPhone { get; private set; }
    public string CallNumber { get; private set; }
    public string CauseOfDeathName { get; private set; }
    public string CoronerName { get; private set; }
    public string CoronerNote { get; private set; }
    public string CoronerOrganization { get; private set; }
    public string CoronerPhone { get; private set; }
    public string CoronerState { get; private set; }
    public string CoronorsCase { get; private set; }
    public string CountyName { get; private set; }
    public int? CurrentReferralTypeId { get; private set; }
    public string CustomField_1 { get; private set; }
    public string CustomField_10 { get; private set; }
    public string CustomField_11 { get; private set; }
    public string CustomField_12 { get; private set; }
    public string CustomField_13 { get; private set; }
    public string CustomField_14 { get; private set; }
    public string CustomField_15 { get; private set; }
    public string CustomField_16 { get; private set; }
    public string CustomField_2 { get; private set; }
    public string CustomField_3 { get; private set; }
    public string CustomField_4 { get; private set; }
    public string CustomField_5 { get; private set; }
    public string CustomField_6 { get; private set; }
    public string CustomField_7 { get; private set; }
    public string CustomField_8 { get; private set; }
    public string CustomField_9 { get; private set; }
    public string DOA { get; private set; }
    public DateTimeOffset? CallLastModified { get; private set; }
    public string MedicalHistory { get; private set; }
    public string NOKCity { get; private set; }
    public string NOKFirstName { get; private set; }
    public string NOKLastName { get; private set; }
    public string NOKPhone { get; private set; }
    public string NOKState { get; private set; }
    public string NOKZip { get; private set; }
    public string NOKAddress { get; private set; }
    public string OrganizationName { get; private set; }
    public string OrganizationUserCode { get; private set; }
    public string PatientHasHeartbeat { get; private set; }
    public string PatientWeight_Decimal { get; private set; }
    public string PersonTypeName { get; private set; }
    public string PronouncingPhysician { get; private set; }
    public string RaceName { get; private set; }
    public Collection<LogEvent> ReferralLogEvents { get; } = new Collection<LogEvent>();
    public int? ReferralAllTissueDispositionId { get; private set; }
    public string ReferralApproachNOK { get; private set; }
    public string ReferralApproachRelation { get; private set; }
    public int? ReferralApproachTypeId { get; private set; }
    public string ReferralAttendingMDPhone { get; private set; }
    public int? ReferralBoneApproachId { get; private set; }
    public int? ReferralBoneAppropriateId { get; private set; }
    public int? ReferralBoneConsentId { get; private set; }
    public int? ReferralBoneConversionId { get; private set; }
    public int? ReferralBoneDispositionId { get; private set; }
    public string ReferralCallerExtension { get; private set; }
    public int ReferralCoronersCase { get; private set; }
    public string ReferralDOB { get; private set; }
    public int ReferralDonor_ILB { get; private set; }
    public DateOnly? ReferralDonorAdmitDate { get; private set; }
    public string ReferralDonorAdmitTime { get; private set; }
    public string ReferralDonorAge { get; private set; }
    public string ReferralDonorAgeUnit { get; private set; }
    public DateOnly? ReferralDonorBrainDeathDate { get; private set; }
    public string ReferralDonorBrainDeathTime { get; private set; }
    public int? ReferralDonorCauseOfDeathId { get; private set; }
    public DateOnly? ReferralDonorDeathDate { get; private set; }
    public string ReferralDonorDeathTime { get; private set; }
    public string ReferralDonorFirstName { get; private set; }
    public string ReferralDonorGender { get; private set; }
    public string ReferralDonorLastName { get; private set; }
    public DateOnly? ReferralDonorLSADate { get; private set; }
    public string ReferralDonorLSATime { get; private set; }
    public string ReferralDonorNameMI { get; private set; }
    public string ReferralDonorOnVentilator { get; private set; }
    public int? ReferralDonorRaceId { get; private set; }
    public string ReferralDonorRecNumber { get; private set; }
    public string ReferralDonorSpecificCOD { get; private set; }
    public string ReferralDonorSSN { get; private set; }
    public string ReferralDonorWeight { get; private set; }
    public string ReferralExtubated { get; private set; }
    public int? ReferralEyesDispositionId { get; private set; }
    public int? ReferralEyesRschApproachId { get; private set; }
    public int? ReferralEyesRschAppropriateId { get; private set; }
    public int? ReferralEyesRschConsentId { get; private set; }
    public int? ReferralEyesRschConversionId { get; private set; }
    public int? ReferralEyesTransApproachId { get; private set; }
    public int? ReferralEyesTransAppropriateId { get; private set; }
    public int? ReferralEyesTransConsentId { get; private set; }
    public int? ReferralEyesTransConversionId { get; private set; }
    public short? ReferralGeneralConsent { get; private set; }
    public int ReferralId { get; private set; }
    public int CallId { get; private set; }
    public DateTimeOffset? ReferralLastModified { get; private set; }
    public int? ReferralOrganApproachId { get; private set; }
    public int? ReferralOrganAppropriateId { get; private set; }
    public int? ReferralOrganConsentId { get; private set; }
    public int? ReferralOrganConversionId { get; private set; }
    public int? ReferralOrganDispositionId { get; private set; }
    public string ReferralPronouncingMDPhone { get; private set; }
    public int? ReferralRschDispositionId { get; private set; }
    public int? ReferralSkinApproachId { get; private set; }
    public int? ReferralSkinAppropriateId { get; private set; }
    public int? ReferralSkinConsentId { get; private set; }
    public int? ReferralSkinConversionId { get; private set; }
    public int? ReferralSkinDispositionId { get; private set; }
    public string ReferralStatus { get; private set; }
    public int ReferralStatusId { get; private set; }
    public int? ReferralTissueApproachId { get; private set; }
    public int? ReferralTissueAppropriateId { get; private set; }
    public int? ReferralTissueConsentId { get; private set; }
    public int? ReferralTissueConversionId { get; private set; }
    public int? ReferralTissueDispositionId { get; private set; }
    public int? ReferralTypeId { get; private set; }
    public string ReferralTypeName { get; private set; }
    public int? ReferralValvesApproachId { get; private set; }
    public int? ReferralValvesAppropriateId { get; private set; }
    public int? ReferralValvesConsentId { get; private set; }
    public int? ReferralValvesConversionId { get; private set; }
    public int? ReferralValvesDispositionId { get; private set; }
    public int? RegistryStatusId { get; private set; }
    public string RegistryStatusType { get; private set; }
    public string ServiceLevelCustomFieldLabel_1 { get; private set; }
    public string ServiceLevelCustomFieldLabel_10 { get; private set; }
    public string ServiceLevelCustomFieldLabel_11 { get; private set; }
    public string ServiceLevelCustomFieldLabel_12 { get; private set; }
    public string ServiceLevelCustomFieldLabel_13 { get; private set; }
    public string ServiceLevelCustomFieldLabel_14 { get; private set; }
    public string ServiceLevelCustomFieldLabel_15 { get; private set; }
    public string ServiceLevelCustomFieldLabel_16 { get; private set; }
    public string ServiceLevelCustomFieldLabel_2 { get; private set; }
    public string ServiceLevelCustomFieldLabel_3 { get; private set; }
    public string ServiceLevelCustomFieldLabel_4 { get; private set; }
    public string ServiceLevelCustomFieldLabel_5 { get; private set; }
    public string ServiceLevelCustomFieldLabel_6 { get; private set; }
    public string ServiceLevelCustomFieldLabel_7 { get; private set; }
    public string ServiceLevelCustomFieldLabel_8 { get; private set; }
    public string ServiceLevelCustomFieldLabel_9 { get; private set; }
    public string StatEmployee { get; private set; }
    public string SourceCode { get; private set; }
    public string CallType { get; private set; }
    public ReferralSecondary SecondaryData { get; set; }
}
