using Statline.StatTrac.Data.Types;
using System;

namespace Statline.StatTrac.StatFile
{
    partial class DataFactory
    {
        #region Enums
        private enum RecurringDateType
        {
            Created = 0,
            LastModified = 1
        }

        /// <summary>
        /// This enum determines how a file is named. The items in the enum are based on RunTime
        /// </summary>
        private enum FileNameDateType
        {
            Current = 0,
            Previous = 1

        }

        private enum FileDataType
        {
            Referral = 1,
            Message = 2,
            ReferralEvent = 3,
            MessageEvent = 4
        }

        /// <summary>
        /// Frequency Files can be generated by
        /// </summary>
        internal enum FileFrequencyType
        {
            Daily,
            Weekly,
            Monthly,
            Hourly,
            Custom,
            Minute
        }
        #endregion Enums

        private delegate void GetEntityDelegate(
              StatFileData ds,
              DateTime startDateTime,
              DateTime endDateTime,
              int webReportGroupID,
              int organizationID,
              int dateTypeID,
              int exportFileID,
              bool seperateFiles,
              int closeCaseTriggerID,
              int closeCaseOverride);
    }
}
