
namespace Statline.Stattrac.Constant
{
	/// <summary>
	/// The list of screen types
	/// </summary>
	public enum AppScreenType
	{
		None = 0,
		Dashboard = 2,
		NewCall = 3,
		Schedules = 4,
        GeneralAlerts = 5,
		LeaseOrgCalls = 6,
		Organizations = 7,
		Administration = 8,
		Help = 9,
		DashboardReferrals = 10,
		DashboardMessagesImports = 11,
		DashboardNoCalls = 12,
		//DashboardConsentPending = 13,
        DashboardFamilyServiceView = 13,
		DashboardFSActiveCases = 14,
		DashboardQA = 15,
		DashboardTCSSActiveCases = 16,
		DashboardRecycledCases = 17,
        DashboardUpdates = 225,
        //DashboardFS = 226,
        //NewCallReferrals = 18,
		NewCallFamilyServices = 19,
        //NewCallMessages = 20,
        //NewCallImportOffers = 21,
		Tcss = 22,
        //NewCallNoCalls = 23,
        //SchedulesSchedules = 24,
        //SchedulesOnCall = 25,
        //GeneralAlertsAdd = 26,
        //GeneralAlertsEdit = 27,
        //GeneralAlertsDelete = 28,
        //LeaseOrgCallsLeaseOrgCalls = 29,
		OrganizationsOrganizationSearch = 30,
        AdministrationSourceCode = 31,
        //AdministrationCriteria = 203,
		AdministrationBillingGroups = 32,
		AdministrationTemplates = 33,
        //AdministrationReportGroups = 34,
        //AdministrationFacilityRotation = 35,
        //AdministrationKeyCodes = 36,
        //AdministrationRuleOutIndications = 37,
		AdministrationQAConfiguration = 38,        
		AdministrationBlockedNumbers = 39,
        //AdministrationAlerts = 226,
        //AdministrationCommitClientChanges = 227,
        //AdministrationViewASPCalls = 228,
		HelpHelp = 40,
		HelpColorAndIconKey = 41,
        //HelpAbout = 42,
		DashboardFSActiveCasesFamilyServicesSummary = 43,
		DashboardFSActiveCasesFamilyServicesDetail = 44,
		TcssTcssOfferInformation = 45,
		TcssCommon = 46,
		TcssLiver = 47,
		TcssKidney = 48,
		TcssTcssOfferInformationOfferInformation = 49,
		TcssTcssOfferInformationImportDonorCard = 50,

		TcssCommonStatusAssoc = 51,
		TcssCommonContactInformation = 52,
		TcssCommonMedicalSocialHistory = 53,
		TcssCommonFluidsBloodDetails = 54,
		TcssCommonTestDiagnosesDetails = 55,
		TcssCommonSerologies = 56,
		TcssCommonUrinalysisCultures = 58,
		TcssCommonAbgVentSettings = 59,
		TcssCommonDonorRecipientHlaDetails = 60,
		TcssCommonVitalSignsDetails = 61,
		TcssCommonLabProfileDetails = 62,

		TcssLiverDonorRecipientHla = 63,
		TcssLiverDonorRecipientHlaSummary = 64,
		TcssLiverVitalSigns = 65,
		TcssLiverLabProfile = 66,
		TcssLiverVitalSignsSummary = 67,
		TcssLiverLabProfileSummary = 68,
		TcssLiverDiagnostics = 69,
		TcssLiverDiagnosticsSummary = 70,

		TcssKidneyDonorRecipientHla = 71,
		TcssKidneyDonorRecipientHlaSummary = 72,
		TcssKidneyVitalSigns = 73,
		TcssKidneyLabProfile = 74,
		TcssKidneyVitalSignsSummary = 75,
		TcssKidneyLabProfileSummary = 76,
		TcssKidneyDiagnostics = 77,
		TcssKidneyDiagnosticsSummary = 78,

		TcssLung = 101,
		TcssHeart = 102,
		TcssIntestine = 103,
		TcssPancreas = 104,
		TcssHeartLung = 105,
		TcssKidneyPancreas = 106,
		TcssMultiOrgan = 107,

		// Lung
		TcssLungDonorRecipientHla = 108,
		TcssLungDonorRecipientHlaSummary = 109,
		TcssLungVitalSigns = 100,
		TcssLungLabProfile = 111,
		TcssLungVitalSignsSummary = 112,
		TcssLungLabProfileSummary = 113,
		TcssLungDiagnostics = 114,
		TcssLungDiagnosticsSummary = 115,

		// Heart
		TcssHeartDonorRecipientHla = 116,
		TcssHeartDonorRecipientHlaSummary = 117,
		TcssHeartVitalSigns = 118,
		TcssHeartLabProfile = 119,
		TcssHeartVitalSignsSummary = 120,
		TcssHeartLabProfileSummary = 121,
		TcssHeartDiagnostics = 122,
		TcssHeartDiagnosticsSummary = 123,

		// Intestine
		TcssIntestineDonorRecipientHla = 124,
		TcssIntestineDonorRecipientHlaSummary = 125,
		TcssIntestineVitalSigns = 126,
		TcssIntestineLabProfile = 127,
		TcssIntestineVitalSignsSummary = 128,
		TcssIntestineLabProfileSummary = 129,
		TcssIntestineDiagnostics = 130,
		TcssIntestineDiagnosticsSummary = 131,

		// Pancreas
		TcssPancreasDonorRecipientHla = 132,
		TcssPancreasDonorRecipientHlaSummary = 133,
		TcssPancreasVitalSigns = 134,
		TcssPancreasLabProfile = 135,
		TcssPancreasVitalSignsSummary = 136,
		TcssPancreasLabProfileSummary = 137,
		TcssPancreasDiagnostics = 138,
		TcssPancreasDiagnosticsSummary = 139,

		// HeartLung
		TcssHeartLungDonorRecipientHla = 140,
		TcssHeartLungDonorRecipientHlaSummary = 141,
		TcssHeartLungVitalSigns = 142,
		TcssHeartLungLabProfile = 143,
		TcssHeartLungVitalSignsSummary = 144,
		TcssHeartLungLabProfileSummary = 145,
		TcssHeartLungDiagnostics = 146,
		TcssHeartLungDiagnosticsSummary = 147,

//		TcssKidneyLabProfileDetails = 85,        

        OrganizationsOrganizationEdit = 86,
        OrganizationsOrganizationProperties = 87,
        OrganizationsOrganizationBaseConfiguration = 88,
        OrganizationsOrganizationOrganizationNumbers = 89,
        OrganizationsOrganizationAliases = 90,
        OrganizationsOrganizationContacts = 91,
        OrganizationsOrganizationDelete = 92,
        OrganizationsOrganizationContactsContactPropertiesEditPopup = 93,
        OrganizationsOrganizationContactsContactProperties = 94,
        OrganizationsOrganizationContactsContactNumbers = 95,
        OrganizationsOrganizationContactsContactCallInstructions = 96,
        OrganizationsOrganizationContactsContactPermission = 97,
        OrganizationContactRoleControl = 98,
        OrganizationContactPermissionControl = 99,
        OrganizationsOrganizationEditPopup = 100,
        OrganizationsOrganizationContactsPhoneEditPopup=84,
        VBQuickLookup = 231,
        ReportIssueFeedbackup = 110,

        //questions
        
        QuestionNavigation = 170,
        QuestionDetails = 171,
        QuestionAddEdit = 172,
        QuestionGroups = 173,
        QuestionMultipleGroups = 174,


        SourceCodeSourceCode = 201,
        SourceCodeAssociatedOrganizations = 202,
        
        //Criteria
        //AdministrationCriteria = 107,
        CriteriaTriageCriteria = 204,
        CriteriaTriageQuestions = 205,
        CriteriaFSCriteria = 206,
        CriteriaAssociatedOrganizations = 207,
        CriteriaAssociatedSourceCodes = 208,

        CriteriaTriageAssociatedQuestions = 209,
        CriteriaTriageQuestionConfiguration = 210,
        CriteriaFSProcessors = 211, 
        CriteriaUpdateCriteriaAndQuestions = 212,
        CriteriaFSModifyCriteria = 213,
        CriteriaFSQuestions = 214,
        CriteriaFSUpdateAssociatedQuestions = 215,
        CriteriaFSUpdateQuestionConfiguration = 216,

        //Start screen config
        //ScreenConfiguration = 175,
	    ContactInformation = 176,
	    PatientInformation = 177,
	    MedicalHistory = 178,
	    Registry = 179,
	    NextofKin = 180,
	    Authorization = 181,
	    CoronerME = 182,
	    FuneralHome = 183,
	    MoreData = 184,
	    Update = 185,
	    OverallDisposition = 186,
	    FamilyServices = 187,
	    ReferralEventLog = 188,
	    AssociatedOrganizations = 189,
	    AssociatedSourceCodes = 190,
        ApplyScreenConfig = 191,
        Message = 192,
        ImportOffer = 193,
        TCSS = 194,
        OtherEventLog = 195,

        FSNextofKin = 220,
        FSCoronerMEAutopsy = 221,
        FSHP = 222,
        FSBodyCare = 223,
        FSCaseManagement = 224,

        // Rule Out Indications
        RuleOutIndications = 218,
        RuleOutIndicationsDetail = 219,
		// KidneyPancreas
		TcssKidneyPancreasDonorRecipientHla = 148,
		TcssKidneyPancreasDonorRecipientHlaSummary = 149,
		TcssKidneyPancreasVitalSigns = 150,
		TcssKidneyPancreasLabProfile = 151,
		TcssKidneyPancreasVitalSignsSummary = 152,
		TcssKidneyPancreasLabProfileSummary = 153,
		TcssKidneyPancreasDiagnostics = 154,
		TcssKidneyPancreasDiagnosticsSummary = 155,

		// MultiOrgan
		TcssMultiOrganDonorRecipientHla = 156,
		TcssMultiOrganDonorRecipientHlaSummary = 157,
		TcssMultiOrganVitalSigns = 158,
		TcssMultiOrganLabProfile = 159,
		TcssMultiOrganVitalSignsSummary = 160,
		TcssMultiOrganLabProfileSummary = 161,
		TcssMultiOrganDiagnostics = 162,
		TcssMultiOrganDiagnosticsSummary = 163,
        //VB Apps...use existing values and these types until C# version is ready
        VBReferral = 300,
        VBReferralReadOnly = 305,
        VBMessage = 301,
        VBMessageReadOnly = 306,
        VBFS = 302,
        VBFSOther = 304,
        VBFSReadOnly = 311,
        VBFSOtherReadOnly = 312,
        VBNew = 18,
        VBSearch = 303,        
        VBOnCall = 25,
        VBSchedule = 24,
        VBHelp = 42,
        VBNoCall = 307,
        VBNoCallReadOnly = 310,
        VBEventLog = 308,
        VBMsgEventLog = 309,
        VBEventLogReadOnly = 313,
        VBMsgEventLogReadOnly = 314,
        VBNewMsg = 20,
        VBNewImp = 21,
        VBNewNoCall = 23,
        VBLeaseOrgCalls = 228,
        VBAlerts = 226,
        VBCriteria = 203,
        VBFacilityRotation = 35,
        VBReportGroups = 34,
        VBScreenConfig = 175,
        VBRuleOutIndications = 37,
        VBKeyCodes = 230,
        VBCommitClientChanges = 227,
        
        //PopUp enums not in AppScreen table
        AdministrationSourceCodeEditPopup = 500

	}
}
