using System;
using System.Collections.ObjectModel;

namespace Statline.StatTrac.Api.DemoClient.Model
{
    public sealed class Referral
    {
        internal Referral() { }
        public string ApproachBy { get; set; }
        public string ApproachTypeName { get; set; }
        public string AttendingPhysician { get; set; }
        public string CallDateTime { get; set; }
        public string Caller { get; set; }
        public string CallerOrganizationUnit { get; set; }
        public string CallerPhone { get; set; }
        public string CallNumber { get; set; }
        public string CauseOfDeathName { get; set; }
        public string CoronerName { get; set; }
        public string CoronerNote { get; set; }
        public string CoronerOrganization { get; set; }
        public string CoronerPhone { get; set; }
        public string CoronerState { get; set; }
        public string CoronorsCase { get; set; }
        public string CountyName { get; set; }
        public int? CurrentReferralTypeId { get; set; }
        public string CustomField_1 { get; set; }
        public string CustomField_10 { get; set; }
        public string CustomField_11 { get; set; }
        public string CustomField_12 { get; set; }
        public string CustomField_13 { get; set; }
        public string CustomField_14 { get; set; }
        public string CustomField_15 { get; set; }
        public string CustomField_16 { get; set; }
        public string CustomField_2 { get; set; }
        public string CustomField_3 { get; set; }
        public string CustomField_4 { get; set; }
        public string CustomField_5 { get; set; }
        public string CustomField_6 { get; set; }
        public string CustomField_7 { get; set; }
        public string CustomField_8 { get; set; }
        public string CustomField_9 { get; set; }
        public string DOA { get; set; }
        public string CallLastModified { get; set; }
        public string MedicalHistory { get; set; }
        public string NOKCity { get; set; }
        public string NOKFirstName { get; set; }
        public string NOKLastName { get; set; }
        public string NOKPhone { get; set; }
        public string NOKState { get; set; }
        public string NOKZip { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationUserCode { get; set; }
        public string PatientHasHeartbeat { get; set; }
        public string PatientWeight_Decimal { get; set; }
        public string PersonTypeName { get; set; }
        public string PronouncingPhysician { get; set; }
        public string RaceName { get; set; }
        public Collection<LogEvent> ReferralLogEvents { get; } = new Collection<LogEvent>();
        public int? ReferralAllTissueDispositionId { get; set; }
        public string ReferralApproachNOK { get; set; }
        public string ReferralApproachRelation { get; set; }
        public int? ReferralApproachTypeId { get; set; }
        public string ReferralAttendingMDPhone { get; set; }
        public int? ReferralBoneApproachId { get; set; }
        public int? ReferralBoneAppropriateId { get; set; }
        public int? ReferralBoneConsentId { get; set; }
        public int? ReferralBoneConversionId { get; set; }
        public int? ReferralBoneDispositionId { get; set; }
        public string ReferralCallerExtension { get; set; }
        public int ReferralCoronersCase { get; set; }
        public string ReferralDOB { get; set; }
        public int ReferralDonor_ILB { get; set; }
        public DateTime? ReferralDonorAdmitDate { get; set; }
        public string ReferralDonorAdmitTime { get; set; }
        public string ReferralDonorAge { get; set; }
        public string ReferralDonorAgeUnit { get; set; }
        public DateTime? ReferralDonorBrainDeathDate { get; set; }
        public string ReferralDonorBrainDeathTime { get; set; }
        public int? ReferralDonorCauseOfDeathId { get; set; }
        public DateTime? ReferralDonorDeathDate { get; set; }
        public string ReferralDonorDeathTime { get; set; }
        public string ReferralDonorFirstName { get; set; }
        public string ReferralDonorGender { get; set; }
        public string ReferralDonorLastName { get; set; }
        public DateTime? ReferralDonorLSADate { get; set; }
        public string ReferralDonorLSATime { get; set; }
        public string ReferralDonorNameMI { get; set; }
        public string ReferralDonorOnVentilator { get; set; }
        public int? ReferralDonorRaceId { get; set; }
        public string ReferralDonorRecNumber { get; set; }
        public string ReferralDonorSpecificCOD { get; set; }
        public string ReferralDonorSSN { get; set; }
        public string ReferralDonorWeight { get; set; }
        public string ReferralExtubated { get; set; }
        public int? ReferralEyesDispositionId { get; set; }
        public int? ReferralEyesRschApproachId { get; set; }
        public int? ReferralEyesRschAppropriateId { get; set; }
        public int? ReferralEyesRschConsentId { get; set; }
        public int? ReferralEyesRschConversionId { get; set; }
        public int? ReferralEyesTransApproachId { get; set; }
        public int? ReferralEyesTransAppropriateId { get; set; }
        public int? ReferralEyesTransConsentId { get; set; }
        public int? ReferralEyesTransConversionId { get; set; }
        public short? ReferralGeneralConsent { get; set; }
        public int ReferralId { get; set; }
        public DateTime? ReferralLastModified { get; set; }
        public string ReferralNOKAddress { get; set; }
        public string ReferralNotesCase { get; set; }
        public int? ReferralOrganApproachId { get; set; }
        public int? ReferralOrganAppropriateId { get; set; }
        public int? ReferralOrganConsentId { get; set; }
        public int? ReferralOrganConversionId { get; set; }
        public int? ReferralOrganDispositionId { get; set; }
        public string ReferralPronouncingMDPhone { get; set; }
        public int? ReferralRschDispositionId { get; set; }
        public int? ReferralSkinApproachId { get; set; }
        public int? ReferralSkinAppropriateId { get; set; }
        public int? ReferralSkinConsentId { get; set; }
        public int? ReferralSkinConversionId { get; set; }
        public int? ReferralSkinDispositionId { get; set; }
        public string ReferralStatus { get; set; }
        public int ReferralStatusId { get; set; }
        public int? ReferralTissueApproachId { get; set; }
        public int? ReferralTissueAppropriateId { get; set; }
        public int? ReferralTissueConsentId { get; set; }
        public int? ReferralTissueConversionId { get; set; }
        public int? ReferralTissueDispositionId { get; set; }
        public int? ReferralTypeId { get; set; }
        public string ReferralTypeName { get; set; }
        public int? ReferralValvesApproachId { get; set; }
        public int? ReferralValvesAppropriateId { get; set; }
        public int? ReferralValvesConsentId { get; set; }
        public int? ReferralValvesConversionId { get; set; }
        public int? ReferralValvesDispositionId { get; set; }
        public int? RegistryStatusId { get; set; }
        public string RegistryStatusType { get; set; }
        public string ServiceLevelCustomFieldLabel_1 { get; set; }
        public string ServiceLevelCustomFieldLabel_10 { get; set; }
        public string ServiceLevelCustomFieldLabel_11 { get; set; }
        public string ServiceLevelCustomFieldLabel_12 { get; set; }
        public string ServiceLevelCustomFieldLabel_13 { get; set; }
        public string ServiceLevelCustomFieldLabel_14 { get; set; }
        public string ServiceLevelCustomFieldLabel_15 { get; set; }
        public string ServiceLevelCustomFieldLabel_16 { get; set; }
        public string ServiceLevelCustomFieldLabel_2 { get; set; }
        public string ServiceLevelCustomFieldLabel_3 { get; set; }
        public string ServiceLevelCustomFieldLabel_4 { get; set; }
        public string ServiceLevelCustomFieldLabel_5 { get; set; }
        public string ServiceLevelCustomFieldLabel_6 { get; set; }
        public string ServiceLevelCustomFieldLabel_7 { get; set; }
        public string ServiceLevelCustomFieldLabel_8 { get; set; }
        public string ServiceLevelCustomFieldLabel_9 { get; set; }
        public string StatEmployee { get; set; }
    }
}
