/***************************************************************************************************
**	Name: TcssListRefusalReason
**	Desc: Data Load for table TcssListRefusalReason
****************************************************************************************************
**	Change History
****************************************************************************************************
**	Date			Author			Description
**	----------	------------	--------------------------------------------------------------------
**	02/17/2010	Tanvir Ather	Initial Data Load
***************************************************************************************************/

SET IDENTITY_INSERT TcssListRefusalReason ON

IF ((SELECT count(*) FROM TcssListRefusalReason) = 0)
BEGIN
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('1', '679', '1', '800', '800', 'Potential recipient’s condition has improved and transplant is currently unnecessary')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('2', '679', '2', '801', '801', 'Potential recipient too sick to attempt transplant at the time of offer, cannot be located, refused transplant, or is temporarily unsuitable for transplant')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('3', '679', '3', '802', '802', 'Either the potential recipient requires a multiple organ transplant or an organ of a different laterality is required (i.e., right lung is specified)')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('4', '679', '4', '803', '803', 'Potential recipient has pending organ offer or is already transplanted at this time')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('5', '679', '5', '810', '810', 'Crossmatch results between donor and potential recipient positive')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('6', '679', '6', '811', '811', 'Number of HLA mismatches between donor and potential recipient unacceptable')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('7', '679', '7', '812', '812', 'No serum for crossmatching')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('8', '679', '8', '813', '813', 'Donor has HLA antigens that are unacceptable to the potential recipient')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('9', '679', '9', '814', '814', 'Potential recipient has high PRA and most likely would have a positive crossmatch')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('10', '679', '10', '820', '820', 'Program unable to accept an organ at this time due to heavy workload')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('11', '679', '11', '822', '822', 'Response was not received from center within the one-hour time period specified in policy')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('12', '679', '12', '823', '823', 'Surgeon unavailable to perform transplant procedure')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('13', '679', '13', '824', '824', 'Too far for the organ recovery team to travel or too far to ship')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('14', '679', '14', '825', '825', 'Transplant center refused due to transportation, logistics, inclement weather issues, or unable to travel for procurement')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('15', '679', '15', '830', '830', 'Donor age, hypertension, prolonged hypotension, high vasopressor/medication dosage, cardiac arrest, evidence of infection/positive cultures, non-heart beating, etiology of death, donor unstable, donor diabetes, other medical history')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('16', '679', '16', '831', '831', 'Donor too large or small, weight incompatible with potential recipient')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('17', '679', '17', '832', '832', 'Donor ABO group incompatible / unacceptable [Only available for LIVER offers; will not display for other organ types]')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('18', '679', '18', '833', '833', 'CDC high risk donor or other reasons related to social history')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('19', '679', '19', '834', '834', 'CMV, HBV, HCV, HIV, HTLV, VDRL, etc. donor testing is positive')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('20', '679', '20', '835', '835', 'Method/quality of preservation, length of cold ischemic time, length of warm ischemic time')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('21', '679', '21', '836', '836', 'Surgical damage, non-surgical trauma, diseased organ, organ vasculature, enbloc kidney''s or any other anatomical reason')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('22', '679', '22', '837', '837', 'Testing unavailable, not done or unacceptable, abnormal biopsy, or other organ-specific reason')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('23', '679', '23', '850', '850', 'Potential recipient was bypassed for priority multi-organ transplant')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('24', '679', '24', '851', '851', 'Potential recipient was bypassed because the donation was directed to a specific recipient.')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('25', '679', '25', '852', '852', 'Potential recipient was bypassed because the organ was from a military donor and was directed to a military recipient.')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('26', '679', '26', '853', '853', 'Potential recipient was bypassed due to the OPO''s OPTN-approved alternative local unit, sharing agreement, or variance')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('27', '679', '27', '860', '860', 'Center bypassed potential recipient due to the urgent medical needs of another potential recipient. (Requires written verification by the transplant program to UNOS Policy Compliance Department.) (Also requires written verification by OPO to UNOS Policy Compliance Department; this bypass and narrative justification will be shared with bypassed centers.)')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('28', '679', '28', '861', '861', 'OPO bypassed potential recipient due to transportation logistics, including distance in relation to ischemic time or weather conditions. (Requires written verification by OPO to UNOS Policy Compliance Department; this bypass and narrative justification will be shared with bypassed centers.)')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('29', '679', '29', '862', '862', 'Potential recipient was bypassed due to urgent donor organ placement. (Requires written verification by OPO to UNOS Policy Compliance Department; this bypass and narrative justification will be shared with bypassed centers.)')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('30', '679', '30', '863', '863', 'Potential recipient bypassed as a result of offer(s) made during an expedited placement attempt. This includes offers of expanded donor organs, OR time constraints or family time constraints. (Requires written verification by OPO to UNOS Policy Compliance Department; this bypass and narrative justification will be shared with bypassed centers.)')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('31', '679', '31', '880', '880', 'Potential recipient was bypassed in order to place the kidney with the extrarenal organ recipient from the same donor.')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('32', '679', '32', '881', '881', 'Potential recipient was bypassed and not offered zero mismatch organs because the policy requirement was satisfied prior to this sequence numbr.')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('33', '679', '33', '882', '882', 'Organ Center uses this code for non-facilitated pancreas center refusals when a facilitated pancreas is offered. [OC use only – does not appear on user list]')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('34', '679', '34', '883', '883', 'Organ Center uses this code for centers that were not offered an organ because their minimum acceptance criteria excluded their potential recipients. [OC use only – does not appear on user list]')
	INSERT INTO TcssListRefusalReason (TcssListRefusalReasonId, LastUpdateStatEmployeeId, SortOrder, FieldValue, UnosValue, Description) VALUES('35', '679', '35', '898', '898', 'Use only if the refusal reason does not fit the above categories. Be sure to write in the other reason, UNOS staff will review the OTHER reason and may recode if necessary.')
END

SET IDENTITY_INSERT TcssListRefusalReason OFF
GO
