//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statline.StatTrac.Web.UI.Controls {
    
    
    public partial class CustomParamsAgeRangeControl {
        
        /// <summary>
        /// ajaxPanelAgeRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebAsyncRefreshPanel ajaxPanelAgeRange;
        
        /// <summary>
        /// ddlAgeRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Infragistics.WebUI.WebCombo.WebCombo ddlAgeRange;
        
        /// <summary>
        /// odsAgeRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource odsAgeRange;
    }
}
