namespace Statline.StatTrac.Domain.LogEvents;

public enum LogEventTypeId
{
    #pragma warning disable format
    Note                        = 1,
    IncomingCall                = 2,
    OutgoingCall                = 3,
    ConsentPending              = 4,
    RecoveryPending             = 5,
    PagePending                 = 6,
    ConsentOutcome              = 7,
    RecoveryOutcome             = 8,
    PageResponse                = 9,
    NoConsentResponse           = 10,
    NoPageResponse              = 12,
    CoronerMEContact            = 13,
    CalloutPending              = 14,
    SecondaryPending            = 15,
    SecondaryOutcome            = 16,
    FaxPending                  = 18,
    OutgoingFax                 = 19,
    FuneralHome                 = 20,
    EmailPending                = 21,
    EmailResponse               = 22,
    UnmatchedResponse           = 23,
    CaseUpdate                  = 24,
    QANote                      = 25,
    ManualRegistryChecked       = 26,
    ConsentObtained             = 27,
    PaperworkCompleted          = 28,
    PaperworkFaxed              = 29,
    FamilyApproached            = 30,
    ClientConsentOutcome        = 31,
    ClientRecoveryOutcome       = 32,
    DeletedEvent                = 33,
    IncomingSecondary           = 34,
    IMConversation              = 35,
    DonorCard                   = 36,
    DonorNetAcceptance          = 37,
    DonorNetDecline             = 38,
    AcknowledgetoEvaluate       = 39,
    LabsPending                 = 40,
    LabsReceived                = 41,
    NoLabsReceived              = 42,
    OnlineReviewPending         = 43,
    OnlineReviewResponse        = 44,
    DeclaredCtodPending         = 45,
    DeclaredCtodConfirmed       = 46,
    CaseHandOff                 = 47,
    OrganMedROPending           = 48,
    OrganMedROConfirmed         = 49,
    ProcessException            = 50,
    EmailSent                   = 51,
    PageSent                    = 52,
    VerificationFormSent        = 53,
    IncomingEReferral           = 54,
    PendingEReferral            = 55,
    EReferralResponse           = 56
    #pragma warning restore format
}