using System;
using System.Collections.Generic;

namespace Stattrac.Services.Donor.Registry.Model
{
    public sealed class DonorAddress : IEquatable<DonorAddress>
    {
        public DonorAddress(
            string? address1, 
            string? address2, 
            string? city, 
            string? state, 
            string? zip)
        {
            Address1 = address1;
            Address2 = address2;
            City = city;
            State = state;
            Zip = zip;
        }

        public string? Address1 { get; }
        public string? Address2 { get; }
        public string? City { get; }
        public string? State { get; }
        public string? Zip { get; }

        public override bool Equals(object obj)
        {
            return Equals(obj as DonorAddress);
        }

        public bool Equals(DonorAddress? other)
        {
            return !(other is null) &&
                   Address1 == other.Address1 &&
                   Address2 == other.Address2 &&
                   City == other.City &&
                   State == other.State &&
                   Zip == other.Zip;
        }

        public override int GetHashCode()
        {
            // Generated by VS
            int hashCode = 1014408957;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Address1!);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Address2!);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(City!);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(State!);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Zip!);
            return hashCode;
        }

      
        public static bool operator ==(DonorAddress? left, DonorAddress? right)
        {
            return EqualityComparer<DonorAddress>.Default.Equals(left!, right!);
        }

        public static bool operator !=(DonorAddress? left, DonorAddress? right)
        {
            return !(left == right);
        }

        public override string ToString()
        {
            return $"Address: {Address1} {Address2}, City: {City}, State: {State}, Zip: {Zip}";
        }

    }
}